chore(api): api image multistage build
langgenius/dify pull request #1069
Opened 2023-08-31 09:43 UTC by JunIce

Api image size reduce to 1.8 GB

2023-08-31 14:54 UTC, takatost requested changes

2023-08-31 14:54 UTC, takatost commented on api/Dockerfile
> +RUN pip install --prefix=/pkg -r requirements.txt
Before pip install, you need to install the following packages. These packages are required for the pip install process on the arm architecture. 
```
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc gcc g++ python3-dev libc-dev libffi-dev \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*
```

2023-08-31 14:54 UTC, takatost commented on api/Dockerfile
> +    && apt-get install -y --no-install-recommends bash curl wget vim gcc g++ python3-dev libc-dev libffi-dev nodejs \
This side can reduce the installation of the aforementioned dependencies, and it can be simplified to `bash curl wget vim nodejs`

2023-09-01 00:56 UTC, JunIce commented on api/Dockerfile
> +    && apt-get install -y --no-install-recommends bash curl wget vim gcc g++ python3-dev libc-dev libffi-dev nodejs \
Have been modified.

2023-09-01 01:04 UTC, JunIce commented
Why we need `vim` pkg, which scenario we use it?

2023-09-01 01:46 UTC, takatost commented
> Why we need `vim` pkg, which scenario we use it?

You can remove it, it was originally for debugging purposes.

2023-09-01 01:47 UTC, takatost approved these changes
thx😊

2023-09-01 02:58 UTC, JunIce commented
> You can remove it, it was originally for debugging purposes.

No need. I just want to know the details. Thank for your explaination.

2023-09-01 03:13 UTC, merged