Mermaid front end rendering
langgenius/dify pull request #1166
Opened 2023-09-12 16:08 UTC by charli117

当生成结果符合mermaid代码块格式要求时，显示SVG转换图标，点击转换图标可在代码块与SVG矢量图间相互切换

2023-09-13 01:24 UTC, charli117 commented
**Promot可以参考如下：**
你将扮演mermaid图形生成器，根据用户场景描述生成符合mermaid格式要求的代码块。

[注意事项]
- 仅输出mermaid代码块，不做其他解释。

Let's think step by step.

**效果演示**

https://github.com/langgenius/dify/assets/24435100/3e44a291-a855-48ee-a91c-33e0074ace53

2023-09-14 02:33 UTC, crazywoola requested changes

2023-09-14 02:33 UTC, crazywoola commented on web/app/components/app/chat/mermaid/index.tsx
> +      <button onClick={handleReRender}>{t('appApi.merMaind.rerender')}</button>
Translation is missing here.

2023-09-14 02:33 UTC, crazywoola commented on web/app/components/app/chat/mermaid/index.tsx
> +}, ref) => {
'ref' is defined but never used.

2023-09-14 02:33 UTC, crazywoola commented on web/app/components/base/markdown.tsx
> +  makefile: 'MarkFile',
typo? :)

2023-09-14 02:33 UTC, crazywoola commented on web/app/components/base/markdown.tsx
> +                      <CopyBtn
The outer box has a CopyBtn Already, so please consider remove this button.

2023-09-14 02:33 UTC, crazywoola commented on web/app/components/app/chat/mermaid/index.tsx
> +  useEffect(() => {
Make sure useEffect is above render function. The handleReRender move before it.

2023-09-14 02:41 UTC, charli117 commented on web/app/components/base/markdown.tsx
> +                      <CopyBtn
外壳原有的CopyBtn是实现代码块的复制，SVGBtn是切换源代码和SVG图像，功能层面本身并不冲突，而且只有在language为mermaid时才会显示SVGBtn

2023-09-14 02:42 UTC, charli117 commented on web/app/components/app/chat/mermaid/index.tsx
> +      <button onClick={handleReRender}>{t('appApi.merMaind.rerender')}</button>
不好意思，这部分忘记合并了，立马补上提交

2023-09-14 06:03 UTC, crazywoola approved these changes
LGTM

2023-09-14 06:09 UTC, merged