[feat] Support Multi-Version Workflows
langgenius/dify pull request #11990
Opened 2024-12-23 05:54 UTC by warren830

# Summary

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

# Screenshots

| Before | After |
|--------|-------|
| ...    | ...   |

# Checklist

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

2024-12-24 02:35 UTC, crazywoola commented
Please fix the lint errors.

2024-12-25 08:03 UTC, crazywoola commented
Link https://github.com/langgenius/dify/issues/10404

2024-12-25 16:34 UTC, laipz8200 requested changes

2024-12-25 16:34 UTC, laipz8200 commented on api/services/workflow_service.py
Please avoid using comments in any language other than English.

2024-12-26 07:25 UTC, warren830 commented on api/services/workflow_service.py
fixed

2024-12-26 07:25 UTC, warren830 commented on api/services/workflow_service.py
> Please avoid using comments in any language other than English.

fixed

2024-12-27 09:41 UTC, crazywoola submitted a review, later dismissed

2024-12-27 10:02 UTC, crazywoola commented on web/app/components/workflow/header/version-history-modal.tsx
> +                  加载更多
Please use i18n instead of raw text.

2024-12-27 10:02 UTC, crazywoola commented on web/app/components/workflow/header/version-history-modal.tsx
> +                暂无历史版本
See above

2024-12-27 10:16 UTC, laipz8200 requested changes

2024-12-27 10:16 UTC, laipz8200 commented on api/services/workflow_service.py
> +                workflow.version = version_datetime.strftime("%Y-%m-%d %H:%M:%S")
update a db model for API response it's not a good way, please consider doing this convert in the front end.

The same issue is on L102.

2024-12-27 10:16 UTC, laipz8200 commented on api/controllers/console/app/workflow.py
> +api.add_resource(PublishedAllWorkflowApi, "/apps/<uuid:app_id>/workflows/publish/all")
IMO, this route name should be `/apps/<uuid:app_id>/workflows`

2024-12-27 12:43 UTC, laipz8200 commented on web/.env.dev
I believe this file should not be uploaded.

2024-12-27 12:54 UTC, warren830 commented on web/.env.dev
my bad

2024-12-27 12:55 UTC, warren830 commented on web/.env.dev
fixed

2024-12-27 13:03 UTC, laipz8200 approved these changes
approve for back-end

2024-12-27 13:04 UTC, crazywoola approved these changes
LGTM

2024-12-27 13:05 UTC, merged