Feat/api jwt
langgenius/dify pull request #1212
Opened 2023-09-22 03:39 UTC by zxhlyh

2023-09-22 07:02 UTC, crazywoola requested changes

2023-09-22 07:02 UTC, crazywoola commented on web/app/components/swr-initor.tsx
> +  const jwtTokenFromLocalStorage = localStorage?.getItem('jwt-token')
```suggestion
  const jwtTokenFromLocalStorage = localStorage?.getItem('console_token')
```

2023-09-22 07:02 UTC, crazywoola commented on web/app/components/swr-initor.tsx
> +  const jwtToken = searchParams.get('jwt_token')
```suggestion
  const jwtToken = searchParams.get('console_token')
```

2023-09-22 07:23 UTC, crazywoola commented on api/controllers/console/auth/login.py
> +        }
```
"iss":  "Cloud" or "CE"
"sub": 'Console API Passport',
```

2023-09-25 04:42 UTC, takatost approved these changes

2023-09-25 04:47 UTC, iamjoel approved these changes

2023-09-25 04:49 UTC, crazywoola approved these changes

2023-09-25 04:49 UTC, merged