fix: bootstrap env
langgenius/dify pull request #127
Opened 2023-05-21 09:14 UTC by yuhao1118

Assuming I haven't missed any information, the current tutorial for starting a project seems to be missing some details. To launch a web project, developers need to manually set a series of NEXT-related environment variables in order for it to start normally. Secondly, the APP_URL for the API project is actually only used for front-end display, so it should be the front-end project's URL (3000). The real APP_URL (5001) should be specified in the web project, as this is the base URL when sending requests.

2023-05-22 03:21 UTC, iamjoel requested changes
Windows doesn't support command: source env.sh. In stead, You can use .env file: https://nextjs.org/docs/app/building-your-application/configuring/environment-variables#env

2023-05-22 03:21 UTC, iamjoel commented on web/package.json
> +    "dev": "source env.sh && next dev",
Windows doesn't support command:  `source env.sh`. In stead, You can use `.env` file: https://nextjs.org/docs/app/building-your-application/configuring/environment-variables#env

2023-05-22 12:35 UTC, yuhao1118 commented on web/package.json
> +    "dev": "source env.sh && next dev",
fixed

2023-05-23 02:47 UTC, iamjoel approved these changes

2023-05-23 02:48 UTC, merged