document segmentApi Add get&update&delete operate
langgenius/dify pull request #1285
Opened 2023-10-08 15:52 UTC by charli117

数据集文档分片API增加查询、删除、更新操作接口

2023-10-09 01:28 UTC, crazywoola requested changes
Please do not modify our api url :)

2023-10-09 02:41 UTC, charli117 commented
> Please do not modify our api url :)

已经调整了，非常抱歉，拷贝过来的时候忘改了

2023-10-10 03:02 UTC, crazywoola commented on web/app/(commonLayout)/datasets/template/template.en.mdx
> +      targetCode={`curl --location --request POST '${props.apiBaseUrl}/datasets/{dataset_id}/documents/{document_id}/segments' \\\n--header 'Authorization: Bearer {api_key}' \\\n--header 'Content-Typ
```suggestion
      targetCode={`curl --location --request GET '${props.apiBaseUrl}/datasets/{dataset_id}/documents/{document_id}/segments' \\\n--header 'Authorization: Bearer {api_key}' \\\n--header 'Content-Type: application/json'`}
```

2023-10-10 05:26 UTC, crazywoola approved these changes

2023-10-10 05:27 UTC, merged