fix ascii codec error, by using utf8
langgenius/dify pull request #1608
Opened 2023-11-23 03:24 UTC by yunyu-Mr

postgresql url config `client_encoding=utf8`

2023-11-23 06:39 UTC, crazywoola requested changes
Can you use environment variables instead of hard code here. Just make sure the behavior here is the same

2023-11-24 11:40 UTC, takatost commented
Can you provide the original scene to reproduce the ASCII codec error?

2023-11-27 07:15 UTC, barnett-yuxiang reviewed
hardcode？ 😭

2023-12-07 12:06 UTC, crazywoola approved these changes

2023-12-08 01:05 UTC, merged