fix: add 'sentence-similarity' in allowed hugging face model tasks
langgenius/dify pull request #1747
Opened 2023-12-13 00:40 UTC by guchenhe

many popular embedding models fall under 'sentence-similarity' tasks on hugging face such as [this one](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2). this fix makes them accessible.

2023-12-13 01:15 UTC, crazywoola approved these changes

2023-12-13 09:18 UTC, takatost requested changes
Sentence Similarity Task is not an Embedding task, ya know. 😄
Although the model used here is indeed an Embedding model, its task is to calculate similarity scores by inputting query and docs. We utilize the ability of the Embedding model to convert embeddings into vectors, and the retrieval and similarity comparison are performed in a vector database.

The principle is that the vector database stores hundreds or thousands of segments, and the query vector after embedding is used to retrieve the top K segments that best match from this large batch of segments. It is a retrieval index technique.
However, Sentence Similarity Task is not suitable for retrieval tasks with such a large number of segments. The core of the vector database lies in the indexing performance and optimization under large data volume, and the similarity comparison algorithm in text is a simple dot product operation (cosine similarity algorithm). Sentence Similarity Task is more suitable for NLP tasks such as classification, intent recognition, and other simple tasks.

2023-12-13 17:44 UTC, jafrank88 commented
How about permitting models tagged as 'bert'?

2023-12-15 05:08 UTC, GarfieldDai commented
You can use huggingface [Inference Endpoints](https://huggingface.co/docs/inference-endpoints/index) to deploy target embedding model. Pay attention, you should select task type as "Feature Extraction" when you do deployment.
![image](https://github.com/langgenius/dify/assets/28395549/c420a873-4f44-4857-a326-307e6a707e16)
![image](https://github.com/langgenius/dify/assets/28395549/e6fcfca2-a09a-43cd-93d4-91216a8c4236)

2023-12-15 18:59 UTC, jafrank88 commented
This might be obvious to others, but why would I want to pay to run an embedding model for my local docs when the models are small, the documents are private, and it does not take that much processing power to embed if you have a GPU.

2023-12-16 16:23 UTC, GarfieldDai commented
Only [Hosted Inference API](https://huggingface.co/docs/api-inference/quicktour) is enabled that can be used in Dify. Not all the embedding model is available.
![image](https://github.com/langgenius/dify/assets/28395549/89678eac-7560-4f69-a0c2-5b32fbf4bd6c)
The model you show is unavailable at Dify for two reason. One task type is not "feature extraction" and the other is the model owner turn off the Inference API.
![image](https://github.com/langgenius/dify/assets/28395549/bfb25a94-df86-474a-8a5c-78893ed63d75)

2023-12-18 02:19 UTC, closed without merging