Chore: Add type files and unit test ci for Node.js SDK
langgenius/dify pull request #2268
Opened 2024-01-29 07:09 UTC by Tseian

2024-01-29 07:19 UTC, Tseian commented
@iamjoel @crazywoola. Pls, conduct a code review.

2024-01-29 11:05 UTC, crazywoola commented
Hello please add my wechat: crazyphage :)

2024-01-29 11:06 UTC, crazywoola reviewed
LGTM, please fix the linter error in actions as well. @Tseian

2024-01-29 11:06 UTC, crazywoola commented on sdks/nodejs-client/index.d.ts
> +  // ...用户对象的属性
Please remove comments here.

2024-01-30 15:45 UTC, bowenliang123 commented on .github/workflows/tool-test-sdks.yaml
> +        run: npm install
using `yarn install` would be faster. `yarn` has been already shipped with `actions/setup-node`.

2024-01-30 15:48 UTC, bowenliang123 commented on .github/workflows/tool-test-sdks.yaml
> +            ${{ runner.os }}-
Unnecessary to cache node modules manually.
Use the caching ability of `actions/setup-node` instead, simply setting:
-    cache (either yarn cache or npm cache supported)
-     cache-dependency-path (file path to package.json)

Refer to official docs. https://github.com/actions/setup-node

2024-01-30 15:49 UTC, bowenliang123 commented on .github/workflows/tool-test-sdks.yaml
> +      - uses: actions/checkout@v2
```suggestion
      - uses: actions/checkout@v4
```
Heads up for latest stable version of the nodejs action.

2024-01-30 15:49 UTC, bowenliang123 commented on .github/workflows/tool-test-sdks.yaml
> +        node-version: [14.x, 16.x, 18.x, 20.x]
```suggestion
        node-version: [14, 16, 18, 20]
```

2024-01-30 15:51 UTC, bowenliang123 commented on .github/workflows/tool-test-sdks.yaml
> +        node-version: [14.x, 16.x, 18.x, 20.x]
Btw , Nodejs 16 is no longer maintained since Oct 2023.
And Nodejs 14 was a legacy version , which could be skipped.

2024-01-31 00:34 UTC, bowenliang123 commented on .github/workflows/tool-test-sdks.yaml
> +      - uses: actions/checkout@v2
```suggestion
      - uses: actions/checkout@v4
```

2024-02-06 10:14 UTC, crazywoola requested changes
Hello please resolve those comments and there is a CI build failure as well.

2024-02-18 06:40 UTC, Tseian commented
> Hello please resolve those comments and there is a CI build failure as well.

Sorry, I've toke a long vacation before spring fest. Those comments will be resolved ASAP.

2024-02-18 07:54 UTC, crazywoola approved these changes

2024-02-18 07:54 UTC, merged