Feat/move tenant id into db
langgenius/dify pull request #2341
Opened 2024-02-01 08:49 UTC by crazywoola

2024-02-01 08:56 UTC, crazywoola commented
@bowenliang123 @charli117  Please take a look at this if you have some spare time.

2024-02-01 14:00 UTC, crazywoola commented on api/controllers/console/auth/login.py
> -        try:
Since we already setup the account in `account_service` while creating the `tenant`, there is no need to do this anymore.

2024-02-01 14:01 UTC, crazywoola commented on api/services/account_service.py
> +        TenantAccountJoin.query.filter_by(account_id=account.id).update({'current': False})
Update all records of current account to false.

2024-02-01 14:43 UTC, charli117 approved these changes

2024-02-01 14:43 UTC, charli117 commented on api/models/account.py
>  import json
json is no longer in use and can be deleted, the rest is fine

2024-02-01 14:52 UTC, bowenliang123 commented on api/services/account_service.py
>              raise AccountNotLinkTenantError("Tenant not found or account is not a member of the tenant.")
How about moving the looking-up to in front of updating all the current accounts to false?

2024-02-02 05:22 UTC, takatost requested changes

2024-02-02 05:22 UTC, takatost commented on api/migrations/versions/16830a790f0f_.py
> +    with op.batch_alter_table('tenant_account_joins', schema=None) as batch_op:
What about moving `current_tenant_id` to `accounts`? 
Setting a flag(current) on `tenant_account_joins` record may result in multiple data being `true` at the same time, lacking atomicity. However, setting `accounts.current_tenant_id` can ensure that an account is only bound to one current tenant.

2024-02-02 05:24 UTC, takatost commented
If we switch suddenly, will the data on the page still be in the context of the other workspace while the backend context has already switched to the workspace where the owner is?

2024-02-02 06:29 UTC, takatost submitted a review, later dismissed

2024-02-02 06:33 UTC, bowenliang123 commented on api/services/account_service.py
> +                    raise AccountNotLinkTenantError("Tenant not found or account is not a member of the tenant.")
Better to move to in front of starting the db transaction.
If no tenant account was found, why not just return the error and pervert create and rollback the transaction?

2024-02-02 06:48 UTC, takatost approved these changes

2024-02-02 06:57 UTC, bowenliang123 approved these changes
LGTM.

2024-02-02 07:00 UTC, merged