tts add voice choose
langgenius/dify pull request #2391
Opened 2024-02-05 06:15 UTC by charli117

2024-02-11 16:55 UTC, takatost requested changes
Thank you so much for your contribution! Btw, could you pls help us update the contribution doc for `tts` as well?

2024-02-11 16:55 UTC, takatost commented on api/core/model_runtime/model_providers/openai/tts/tts-1-hd.yaml
> +      language: ['zh-CN-CN', 'en-US']
looks like there's a mistake here.

2024-02-11 16:55 UTC, takatost commented on api/core/model_runtime/model_providers/openai/tts/tts-1.yaml
> +      language: ['zh-CN-CN', 'en-US']
there's a mistake too.

2024-02-12 00:04 UTC, charli117 commented
> Thank you so much for your contribution! Btw, could you pls help us update the contribution doc for `tts` as well?

It has been fixed, and update tts doc

2024-02-12 05:53 UTC, takatost requested changes
<img width="1050" alt="image" src="https://github.com/langgenius/dify/assets/5485478/bdddf08f-1a43-4a95-b123-00f6d0072e57">
App that has been configured with `text-to-speech` will throw an error due to failed verification. Maybe we can add a default value?

2024-02-12 05:55 UTC, takatost commented
```
ERROR:root:internal server error, 'voice'.
Traceback (most recent call last):
  File "/app/api/controllers/console/app/audio.py", line 98, in post
    voice=app_model.app_model_config.text_to_speech_dict['voice'],
KeyError: 'voice'
ERROR:app:Exception on /console/api/apps/3b950e1e-7f8a-4d22-b13c-12710e3bf6a6/text-to-audio [POST]
Traceback (most recent call last):
  File "/app/api/controllers/console/app/audio.py", line 98, in post
    voice=app_model.app_model_config.text_to_speech_dict['voice'],
KeyError: 'voice'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/console/setup.py", line 84, in decorated
    return view(*args, **kwargs)
  File "/app/api/libs/login.py", line 91, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/api/controllers/console/wraps.py", line 21, in decorated
    return view(*args, **kwargs)
  File "/app/api/controllers/console/app/audio.py", line 126, in post
    raise InternalServerError()
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

And after completing the tts configuration, when debugging on the orchestration page, it will throw an Internal Server Error.

2024-02-12 06:43 UTC, charli117 commented
> ```
> ERROR:root:internal server error, 'voice'.
> Traceback (most recent call last):
>   File "/app/api/controllers/console/app/audio.py", line 98, in post
>     voice=app_model.app_model_config.text_to_speech_dict['voice'],
> KeyError: 'voice'
> ERROR:app:Exception on /console/api/apps/3b950e1e-7f8a-4d22-b13c-12710e3bf6a6/text-to-audio [POST]
> Traceback (most recent call last):
>   File "/app/api/controllers/console/app/audio.py", line 98, in post
>     voice=app_model.app_model_config.text_to_speech_dict['voice'],
> KeyError: 'voice'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
>   File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
>     resp = resource(*args, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 110, in view
>     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
>   File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
>     resp = meth(*args, **kwargs)
>   File "/app/api/controllers/console/setup.py", line 84, in decorated
>     return view(*args, **kwargs)
>   File "/app/api/libs/login.py", line 91, in decorated_view
>     return current_app.ensure_sync(func)(*args, **kwargs)
>   File "/app/api/controllers/console/wraps.py", line 21, in decorated
>     return view(*args, **kwargs)
>   File "/app/api/controllers/console/app/audio.py", line 126, in post
>     raise InternalServerError()
> werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
> ```
> 
> And after completing the tts configuration, when debugging on the orchestration page, it will throw an Internal Server Error.

@takatost fixed initialization null error, this is because the voice is not configured, resulting in the absence of two textToSpeechConfig property fields, voice and lanuage

2024-02-12 07:29 UTC, takatost commented
> > ```
> > ERROR:root:internal server error, 'voice'.
> > Traceback (most recent call last):
> >   File "/app/api/controllers/console/app/audio.py", line 98, in post
> >     voice=app_model.app_model_config.text_to_speech_dict['voice'],
> > KeyError: 'voice'
> > ERROR:app:Exception on /console/api/apps/3b950e1e-7f8a-4d22-b13c-12710e3bf6a6/text-to-audio [POST]
> > Traceback (most recent call last):
> >   File "/app/api/controllers/console/app/audio.py", line 98, in post
> >     voice=app_model.app_model_config.text_to_speech_dict['voice'],
> > KeyError: 'voice'
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
> >     rv = self.dispatch_request()
> >   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
> >     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
> >   File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
> >     resp = resource(*args, **kwargs)
> >   File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 110, in view
> >     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
> >   File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
> >     resp = meth(*args, **kwargs)
> >   File "/app/api/controllers/console/setup.py", line 84, in decorated
> >     return view(*args, **kwargs)
> >   File "/app/api/libs/login.py", line 91, in decorated_view
> >     return current_app.ensure_sync(func)(*args, **kwargs)
> >   File "/app/api/controllers/console/wraps.py", line 21, in decorated
> >     return view(*args, **kwargs)
> >   File "/app/api/controllers/console/app/audio.py", line 126, in post
> >     raise InternalServerError()
> > werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And after completing the tts configuration, when debugging on the orchestration page, it will throw an Internal Server Error.
> 
> @takatost fixed initialization null error, this is because the voice is not configured, resulting in the absence of two textToSpeechConfig property fields, voice and lanuage

This issue has been resolved and can now play perfectly. 👍🏻
However, the previous `Validation exception` still exists. If this PR is merged and deployed, it will cause the existing app to throw an error during voice playing. Developers will need to manually set the voice and language for it to run properly.

2024-02-13 17:01 UTC, charli117 commented
> > > ```
> > > ERROR:root:internal server error, 'voice'.
> > > Traceback (most recent call last):
> > >   File "/app/api/controllers/console/app/audio.py", line 98, in post
> > >     voice=app_model.app_model_config.text_to_speech_dict['voice'],
> > > KeyError: 'voice'
> > > ERROR:app:Exception on /console/api/apps/3b950e1e-7f8a-4d22-b13c-12710e3bf6a6/text-to-audio [POST]
> > > Traceback (most recent call last):
> > >   File "/app/api/controllers/console/app/audio.py", line 98, in post
> > >     voice=app_model.app_model_config.text_to_speech_dict['voice'],
> > > KeyError: 'voice'
> > > 
> > > During handling of the above exception, another exception occurred:
> > > 
> > > Traceback (most recent call last):
> > >   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
> > >     rv = self.dispatch_request()
> > >   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
> > >     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
> > >   File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
> > >     resp = resource(*args, **kwargs)
> > >   File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 110, in view
> > >     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
> > >   File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
> > >     resp = meth(*args, **kwargs)
> > >   File "/app/api/controllers/console/setup.py", line 84, in decorated
> > >     return view(*args, **kwargs)
> > >   File "/app/api/libs/login.py", line 91, in decorated_view
> > >     return current_app.ensure_sync(func)(*args, **kwargs)
> > >   File "/app/api/controllers/console/wraps.py", line 21, in decorated
> > >     return view(*args, **kwargs)
> > >   File "/app/api/controllers/console/app/audio.py", line 126, in post
> > >     raise InternalServerError()
> > > werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 并且完成tts配置后，在编排页面调试时，会抛出Internal Server Error。
> > 
> > 
> > @takatost修复初始化为null的错误，这是因为没有配置语音，导致缺少voice和lanuage这两个textToSpeechConfig属性字段
> 
> 这个问题已经解决了，现在可以完美播放了。 👍🏻 不过，以前的`Validation exception`依然存在。如果合并并部署此 PR，将导致现有应用程序在语音播放时抛出错误。开发人员需要手动设置语音和语言才能正常运行。

@

2024-02-13 17:05 UTC, charli117 commented
> > > ```
> > > ERROR:root:internal server error, 'voice'.
> > > Traceback (most recent call last):
> > >   File "/app/api/controllers/console/app/audio.py", line 98, in post
> > >     voice=app_model.app_model_config.text_to_speech_dict['voice'],
> > > KeyError: 'voice'
> > > ERROR:app:Exception on /console/api/apps/3b950e1e-7f8a-4d22-b13c-12710e3bf6a6/text-to-audio [POST]
> > > Traceback (most recent call last):
> > >   File "/app/api/controllers/console/app/audio.py", line 98, in post
> > >     voice=app_model.app_model_config.text_to_speech_dict['voice'],
> > > KeyError: 'voice'
> > > 
> > > During handling of the above exception, another exception occurred:
> > > 
> > > Traceback (most recent call last):
> > >   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
> > >     rv = self.dispatch_request()
> > >   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
> > >     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
> > >   File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
> > >     resp = resource(*args, **kwargs)
> > >   File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 110, in view
> > >     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
> > >   File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
> > >     resp = meth(*args, **kwargs)
> > >   File "/app/api/controllers/console/setup.py", line 84, in decorated
> > >     return view(*args, **kwargs)
> > >   File "/app/api/libs/login.py", line 91, in decorated_view
> > >     return current_app.ensure_sync(func)(*args, **kwargs)
> > >   File "/app/api/controllers/console/wraps.py", line 21, in decorated
> > >     return view(*args, **kwargs)
> > >   File "/app/api/controllers/console/app/audio.py", line 126, in post
> > >     raise InternalServerError()
> > > werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And after completing the tts configuration, when debugging on the orchestration page, it will throw an Internal Server Error.
> > 
> > 
> > @takatost fixed initialization null error, this is because the voice is not configured, resulting in the absence of two textToSpeechConfig property fields, voice and lanuage
> 
> This issue has been resolved and can now play perfectly. 👍🏻 However, the previous `Validation exception` still exists. If this PR is merged and deployed, it will cause the existing app to throw an error during voice playing. Developers will need to manually set the voice and language for it to run properly.

@takatost This bug has been fixed，adjusted the initial value of TextToSpeechEntity BaseModel

2024-02-14 04:43 UTC, takatost requested changes
<img width="562" alt="image" src="https://github.com/langgenius/dify/assets/5485478/c77fb3d8-15fa-44f3-99c7-355622adfe84">

Hey, I've run into a new issue. When I choose OpenAI's Onyx for English and most of the voices for Chinese, I'm facing some problems.

2024-02-14 16:25 UTC, charli117 commented
> <img alt="image" width="562" src="https://private-user-images.githubusercontent.com/5485478/304623322-c77fb3d8-15fa-44f3-99c7-355622adfe84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MjgxMjMsIm5iZiI6MTcwNzkyNzgyMywicGF0aCI6Ii81NDg1NDc4LzMwNDYyMzMyMi1jNzdmYjNkOC0xNWZhLTQ0ZjMtOTljNy0zNTU2MjJhZGZlODQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTRUMTYyMzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGI2NmFkYjE2ZTU5MTg0YjdmMjQ5ZGIzYTQ1ZmEwNTJkZTgyYzdmNWU2ZGZkNjUwZmU2OGI4NDczMDcxZTYxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LAT7UtQn2SGomgXHUNy55THe3rROMbHJZbv-iinMjfY">
> Hey, I've run into a new issue. When I choose OpenAI's Onyx for English and most of the voices for Chinese, I'm facing some problems.

@takatost This error is a bit strange, did you pull the openai tts yaml file in full? I'll take the type restrictions off. You try again

2024-02-15 14:41 UTC, takatost approved these changes
Testing is all good now! 🎉
Thank you so much for your contribution!

2024-02-15 14:41 UTC, merged

2024-02-15 15:18 UTC, takatost commented
@charli117 Hey, I found a new issue. Even when I switch to the English interface, the language dropdown still shows Chinese. 🤔