Support openrouter streaming
langgenius/dify pull request #2432
Opened 2024-02-11 10:37 UTC by johnpccd

2024-02-14 12:16 UTC, crazywoola commented on api/core/model_runtime/model_providers/openai_api_compatible/llm/llm.py
> +            if chunk:
This is a deprecate if statement. Please move the `chunk = chunk.strip().lstrip(': OPENROUTER PROCESSING').lstrip()` into next line.

2024-02-14 12:17 UTC, crazywoola requested changes
Please remove duplicate if statement.

2024-02-15 15:16 UTC, guchenhe commented
Hi thanks for the PR! I looked into it, and it seem that this message openrouter sends is a comment as per SSE spec. 
<img width="1047" alt="image" src="https://github.com/langgenius/dify/assets/13230914/51c546e6-4a8c-497f-8ec0-06159469e88b">

Instead of ignoring only openrouter comments, would you be down to expand this a bit to ignore all SSE comments?

2024-02-15 17:07 UTC, guchenhe approved these changes

2024-02-16 01:21 UTC, crazywoola approved these changes

2024-02-16 02:00 UTC, merged