FEAT: add image styling in markdown
langgenius/dify pull request #2441
Opened 2024-02-13 15:31 UTC by Yash-1511

In this change, i have added some image styling. 

Before:
![Screenshot from 2024-02-13 12-23-33](https://github.com/langgenius/dify/assets/82636823/754f22bb-edf0-4ddd-b044-36ea6898070b)

After:
![Screenshot from 2024-02-13 12-22-04](https://github.com/langgenius/dify/assets/82636823/8afd6fe3-58f2-4827-8460-de4e56055d2b)

2024-02-14 04:20 UTC, takatost requested changes
Thank you so much for your contribution! 
There's an eslint error that needs to be fixed, could you please take a look at it?
 https://github.com/langgenius/dify/actions/runs/7888879799/job/21527443340?pr=2441

2024-02-14 08:14 UTC, Yash-1511 commented
Yeah... Sure i will check and update it.

2024-02-15 00:49 UTC, bowenliang123 commented
> Thank you so much for your contribution! There's an eslint error that needs to be fixed, could you please take a look at it? https://github.com/langgenius/dify/actions/runs/7888879799/job/21527443340?pr=2441

BTW, we could have an extra hint step for failed jobs of `Web Sytle Check` to tell the contributor what to do or how to fix them by using `yarn fix`.

2024-02-15 00:53 UTC, bowenliang123 commented on web/yarn.lock
> +resolve@^1.1.7, resolve@^1.10.0, resolve@^1.22.1, resolve@^1.22.2, resolve@^1.22.4:
It seems unnecessary and brings no gains, as there is no change in `package.json`.

2024-02-19 04:55 UTC, crazywoola submitted a review, later dismissed

2024-02-19 06:39 UTC, crazywoola approved these changes

2024-02-19 06:57 UTC, takatost approved these changes
LGTM

2024-02-19 07:06 UTC, bowenliang123 commented
How about just use `max-width` attribute instead?

2024-02-19 07:07 UTC, merged

2024-02-19 07:08 UTC, bowenliang123 commented
A hardcoded 250 in `width` and `height` may not be satisfied for different responsive or size of screens.