bump redis client to 5.0 and enable hiredis support
langgenius/dify pull request #2518
Opened 2024-02-22 03:14 UTC by bowenliang123

# Description

- bump redis client from 4.5.x to 5.0.x
   - to support Redis 7.1+, https://github.com/redis/redis-py?tab=readme-ov-file#supported-redis-versions
   - minimum required Redis server version 5.0 is not changed
- enable hiredis support for faster performance with compiled response parser
   - hiredis benchmarks
   - hiredis is a minimalistic redis C client maintained by Redis official
   - hiredis python package is also maintained by Redis official (https://github.com/redis/hiredis-py), and will be installed
   - https://github.com/redis/redis-py?tab=readme-ov-file#installation

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)

# How Has This Been Tested?

- run ci jobs

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

2024-02-22 04:42 UTC, takatost commented
Thanks for the contribution! 
We will schedule the upgrade of the common dependencies for next month when we have some free time to conduct functionality, performance, and compatibility tests. BTW, It would be really helpful if you could provide integration test code as well.

2024-02-22 05:04 UTC, bowenliang123 commented
I found no advanced features or commands used with the Redis.
All the commands used are basic ones, e.g. get/set/setex.
Therefore no particular tests required for them.
And this PR introduce no breaking changes.

2024-02-22 05:04 UTC, bowenliang123 commented
Are you suggesting closing this PR this time?
It's alright to me.

2024-02-22 06:48 UTC, crazywoola approved these changes, later dismissed
LGTM @takatost What about you.

2024-02-22 07:30 UTC, takatost requested changes
I hope we can first collect all the places in the code where Redis is used, organize the methods that use Redis for unified testing, and check if Redis SSL configuration is supported, if the connection pool meets expectations, if decode() after get() works properly, and so on.

2024-02-22 07:45 UTC, bowenliang123 commented
I have organized all the Redis client usages in commands:
- 67 places in total
- get 21 / setex 25 / setnx 1 / expire 1  / delete

They are all basic commands.
This PR introduces no new features or breaking changes from command to usage.

I agree that your suggestion for full testing for Redis clients. And I do suggest we should cover all the feature used.
Not just the commands, pools, but also the support for RESP3 protocol、cluster mode、sentinel and etc.

But that should not be a blocker issue for this bump.
It's just a minor bump, for the sake.

2024-02-22 09:23 UTC, takatost commented
> I have organized all the Redis client usages in commands:
> 
> * 67 places in total
> * get 21 / setex 25 / setnx 1 / expire 1  / delete
> 
> They are all basic commands. This PR introduces no new features or breaking changes from command to usage.
> 
> I agree that your suggestion for full testing for Redis clients. And I do suggest we should cover all the feature used. Not just the commands, pools, but also the support for RESP3 protocol、cluster mode、sentinel and etc.
> 
> But that should not be a blocker issue for this bump. It's just a minor bump, for the sake.

Could you pls provide some evidence (test results / test code...) regarding Redis? It's quite broad, so it would be helpful for us to review. Otherwise, we'll have to find some time to manually test if the functionality is working properly.

2024-03-28 03:40 UTC, takatost approved these changes
LGTM

2024-03-28 03:40 UTC, merged