add max_tokens parameter rule for zhipuai glm4 and glm4v
langgenius/dify pull request #2861
Opened 2024-03-16 10:05 UTC by orangeclk

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #2860 

## Type of Change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

My testing environment is WSL2 Ubuntu 22.04 LTS, Python 3.10.13, Node v21.7.1.
I have instructed glm4 and glm4v to output long content, and by setting different values for max_tokens, it is possible to observe varying lengths of returned results.

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

2024-03-16 10:43 UTC, crazywoola requested changes

2024-03-16 10:43 UTC, crazywoola commented on web/yarn.lock
Please remove this file, since there is no changes related to frontend.

2024-03-16 11:00 UTC, orangeclk commented on web/yarn.lock
I've removed the file. Thanks.

2024-03-16 13:35 UTC, bowenliang123 commented on web/yarn.lock
@crazywoola is suggesting removing this file from the changed files and remaining untouched, rather than removing it from the source code.

2024-03-16 13:36 UTC, bowenliang123 commented on web/yarn.lock
Please revert the changes in `yarn.lock` and use `yarn install --frozen-lockfile` to install packages locally without changing the yarn lockfile.

2024-03-17 05:44 UTC, orangeclk commented on web/yarn.lock
Thank you! I'm not sure why the `yarn.lock` file was changed. According to the commit history, it seems to have appeared after running `dev/reformat`, but theoretically, `dev/reformat` should not have caused the changes. I tried again and was unable to reproduce the changes. I will pay attention to similar situations in the future.

2024-03-18 03:53 UTC, Yeuoly approved these changes
LGTM

2024-03-18 05:19 UTC, crazywoola approved these changes

2024-03-18 05:19 UTC, merged