generalize module_import_helper for loading module from source
langgenius/dify pull request #2862
Opened 2024-03-16 14:33 UTC by bowenliang123

# Description

- generalize module_import_helper for loading module from source

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

2024-03-18 09:04 UTC, crazywoola approved these changes, later dismissed

2024-03-19 10:33 UTC, takatost requested changes
some err happened when module loading

2024-03-19 10:33 UTC, takatost commented on api/core/utils/module_import_helper.py
> +        module = importlib.util.module_from_spec(spec)
```
ERROR:root:Failed to load module openai_moderation from /Users/takatost/Projects/dify/api/core/moderation/openai_moderation/openai_moderation.py: 'NoneType' object has no attribute 'loader'
Traceback (most recent call last):
  File "/Users/takatost/Projects/dify/api/core/utils/module_import_helper.py", line 26, in import_module_from_source
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 568, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
WARNING:root:Missing subclass of Moderation in /Users/takatost/Projects/dify/api/core/moderation/openai_moderation/openai_moderation.py, Skip.
ERROR:root:Failed to load module keywords from /Users/takatost/Projects/dify/api/core/moderation/keywords/keywords.py: 'NoneType' object has no attribute 'loader'
Traceback (most recent call last):
  File "/Users/takatost/Projects/dify/api/core/utils/module_import_helper.py", line 26, in import_module_from_source
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 568, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
WARNING:root:Missing subclass of Moderation in /Users/takatost/Projects/dify/api/core/moderation/keywords/keywords.py, Skip.
```

load err in moderation extensions.

2024-03-19 10:35 UTC, bowenliang123 commented on api/core/utils/module_import_helper.py
> +        module = importlib.util.module_from_spec(spec)
Let me check again. To see whether the same on my local env.

2024-03-19 10:35 UTC, bowenliang123 commented on api/core/utils/module_import_helper.py
> +        module = importlib.util.module_from_spec(spec)
Or we could just skip the potential lazy loader support.

2024-03-20 14:11 UTC, bowenliang123 commented on api/core/utils/module_import_helper.py
> +        module = importlib.util.module_from_spec(spec)
Hi, the error comes from setting the spec when there's no existed spec found.
It has been fixed by reverting the condition.

2024-03-20 14:39 UTC, bowenliang123 commented
Tests added. Please review again.

2024-03-28 03:37 UTC, takatost approved these changes
LGTM

2024-03-28 03:37 UTC, merged