feat: AWS Bedrock Claude3
langgenius/dify pull request #2864
Opened 2024-03-16 19:41 UTC by soulteary

# Description

Support calling AWS Bedrock Claude3 model, issue #2856

## Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

<img width="868" alt="image" src="https://github.com/langgenius/dify/assets/1500781/d2e1c492-d2b8-4a68-9141-db24bc6f7710">

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

2024-03-17 08:38 UTC, guchenhe commented
![CleanShot 2024-03-17 at 01 31 54@2x](https://github.com/langgenius/dify/assets/13230914/8e2dbfb6-82f0-43ac-8ce0-1c558bcd9d94)

Thanks for the PR. I wasn't able to get either Claude 3 Sonnet or Haiku to work due to the above error msg. Would you take a look into it?

2024-03-17 09:28 UTC, soulteary commented
> ![CleanShot 2024-03-17 at 01 31 54@2x](https://private-user-images.githubusercontent.com/13230914/313456725-8e2dbfb6-82f0-43ac-8ce0-1c558bcd9d94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2Njc5MjAsIm5iZiI6MTcxMDY2NzYyMCwicGF0aCI6Ii8xMzIzMDkxNC8zMTM0NTY3MjUtOGUyZGJmYjYtODJmMC00M2FjLThjZTAtMWM1NThiY2Q5ZDk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDA5MjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhZDZjYzk4NjM3YzlmOTgyNTMyNjg5MzMxMWU0M2FiYTlhYWYyNzZkY2Y2YmZlMzI2YWY0NGQwZjc3NzM0MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bsfmpdy4tQ9nyCUNzndkCMqba129UuCNmEZwFu15fQM)
> 
> Thanks for the PR. I wasn't able to get either Claude 3 Sonnet or Haiku to work due to the above error msg. Would you take a look into it?

@guchenhe This bug comes from Claude SDK. Refer to the requirement.txt I submitted. You need to update an SDK version to the latest one.

I recommend verifying directly in a fresh Docker environment, it's very easy.

2024-03-17 17:00 UTC, guchenhe requested changes

2024-03-17 17:00 UTC, guchenhe commented on api/core/model_runtime/model_providers/bedrock/llm/anthropic.claude-3-haiku-v1.yaml
> +  en_US: Claude3 Haiku
```suggestion
  en_US: Claude 3 Haiku
```

2024-03-17 17:00 UTC, guchenhe commented on api/core/model_runtime/model_providers/bedrock/llm/anthropic.claude-3-haiku-v1.yaml
> +      en_US: The system prompt for the request. A system prompt is a way of providing context and instructions to Anthropic Claude, such as specifying a particular goal or role.
This seems the same as system prompt in expert mode. Can it be removed from both yamls?

2024-03-17 17:00 UTC, guchenhe commented on api/core/model_runtime/model_providers/bedrock/llm/anthropic.claude-3-sonnet-v1.yaml
> +  en_US: Claude3 Sonnet
```suggestion
  en_US: Claude 3 Sonnet
```

2024-03-17 17:02 UTC, guchenhe commented
> > ![CleanShot 2024-03-17 at 01 31 54@2x](https://private-user-images.githubusercontent.com/13230914/313456725-8e2dbfb6-82f0-43ac-8ce0-1c558bcd9d94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2Njc5MjAsIm5iZiI6MTcxMDY2NzYyMCwicGF0aCI6Ii8xMzIzMDkxNC8zMTM0NTY3MjUtOGUyZGJmYjYtODJmMC00M2FjLThjZTAtMWM1NThiY2Q5ZDk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDA5MjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhZDZjYzk4NjM3YzlmOTgyNTMyNjg5MzMxMWU0M2FiYTlhYWYyNzZkY2Y2YmZlMzI2YWY0NGQwZjc3NzM0MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bsfmpdy4tQ9nyCUNzndkCMqba129UuCNmEZwFu15fQM)
> > Thanks for the PR. I wasn't able to get either Claude 3 Sonnet or Haiku to work due to the above error msg. Would you take a look into it?
> 
> @guchenhe This bug comes from Claude SDK. Refer to the requirement.txt I submitted. You need to update an SDK version to the latest one.
> 
> I recommend verifying directly in a fresh Docker environment, it's very easy.

Thanks! It's working like a charm now. I left some suggestions and we'll be able to merge as soon as those are resolved and linting passes

2024-03-18 08:02 UTC, crazywoola approved these changes, later dismissed

2024-03-18 09:10 UTC, crazywoola approved these changes

2024-03-18 10:16 UTC, takatost approved these changes
LGTM

2024-03-18 10:16 UTC, merged