fix: progress bar issue
langgenius/dify pull request #2957
Opened 2024-03-25 05:48 UTC by yikayiyo

# Description

On the `/datasets` page, clicking on a delete icon triggers the unexpected appearance of the progress bar. The latest version of the `next-nprogress-bar` package provides a solution to this issue. However, it might be worth considering redesigning the `DatasetCard` component, as encapsulating numerous elements within a single `Link` component is not considered a best practice.

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency upgrade

2024-03-25 06:54 UTC, crazywoola requested changes

2024-03-25 06:54 UTC, crazywoola commented on web/yarn.lock
There is no actual changes of package.json, so this should not be committed into the vc system.

2024-03-25 07:14 UTC, crazywoola commented
Hello please add my wechat crazyphage I will invite you to the contributors' group.

2024-03-25 07:21 UTC, yikayiyo commented on web/yarn.lock
I ran `yarn upgrade next-nprogress-bar` and it didn't change the package.json file. Should I update the package.json file?

2024-03-25 14:19 UTC, crazywoola commented on web/yarn.lock
Yes, in this case you should change the deps as well.

2024-03-26 04:34 UTC, yikayiyo commented on web/yarn.lock
I've updated the deps.

2024-03-26 09:26 UTC, crazywoola approved these changes

2024-03-26 09:26 UTC, merged