feat: 支持xlsx文件格式解析
langgenius/dify pull request #304
Opened 2023-06-06 06:37 UTC by saifeiLee

1. 支持xlsx文件的解析，以List输出

2023-06-07 02:10 UTC, takatost commented
Thanks for your contribution! We'll take a look and test it out to make sure everything is good to go and add some design support, which might take 1-2 days.

2023-06-08 06:24 UTC, crazywoola requested changes
Please discard changes in web/
I will have a separate PR for this part. :)

2023-06-08 06:48 UTC, saifeiLee commented
> 

OK, I have updated the MR and discarded the changes in /web. Please check it.

2023-06-08 07:23 UTC, crazywoola approved these changes

2023-06-09 07:57 UTC, merged