feat:api Add support for extracting EPUB files in ExtractProcessor
langgenius/dify pull request #3254
Opened 2024-04-09 13:09 UTC by vaayne

# Description

Add support for extracting EPUB files in ExtractProcessor

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

2024-04-11 01:10 UTC, crazywoola commented
Hello thank you for your contribution, you can add my wechat: crazyphage
I will invite you to our contributor's group.

2024-04-11 02:04 UTC, crazywoola requested changes
https://github.com/langgenius/dify/blob/6c4e6bf1d6ca92716ed05b47c5b46035047c3873/api/services/file_service.py#L23

This does not need to add since it only supported in unstructured io

https://github.com/langgenius/dify/blob/6c4e6bf1d6ca92716ed05b47c5b46035047c3873/api/services/file_service.py#L25

You need to add it to supported ext list as well.

2024-04-11 09:53 UTC, JohnJyong approved these changes

2024-04-11 09:54 UTC, JohnJyong approved these changes

2024-04-11 09:55 UTC, JohnJyong approved these changes

2024-04-11 09:55 UTC, JohnJyong approved these changes

2024-04-12 03:24 UTC, crazywoola approved these changes

2024-04-12 03:25 UTC, merged