Update README.md
langgenius/dify pull request #3893
Opened 2024-04-26 09:53 UTC by dockercore

feat: Add upgrade instructions for Docker deployment
﻿
﻿
﻿
Detailed steps for stopping the service, backing up data, and upgrading to a new version
﻿
Includes commands for backing up Docker image ID, database files, and docker-compose.yaml
﻿
Provides an example of downloading a specific version (0.6.5) of the docker-compose.yaml file
﻿
﻿
﻿
﻿
﻿
﻿
﻿
## Type of Change
﻿
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
﻿
﻿
# Suggested Checklist:
﻿
- [ ] `optional` I have made corresponding changes to the documentation 
﻿
﻿

2024-04-26 09:55 UTC, crazywoola requested changes
And please update other languages accordingly.

2024-04-26 09:55 UTC, crazywoola commented on README.md
> +docker-compose down
Please use `docker compose` as docker docs suggests.

2024-04-26 10:34 UTC, dockercore commented on README.md
> +docker-compose down
OK

2024-05-14 23:49 UTC, crazywoola approved these changes, later dismissed

2024-05-14 23:49 UTC, crazywoola commented on README.md
> +docker-compose down
```suggestion
docker compose down
```

2024-05-14 23:49 UTC, crazywoola commented on README.md
> + docker-compose up -d
```suggestion
 docker compose up -d
```

2024-05-14 23:56 UTC, crazywoola approved these changes

2024-05-20 04:19 UTC, guchenhe commented
README might not be the best place for this, would you open a PR to put this in our docs instead? https://docs.dify.ai/getting-started/install-self-hosted/docker-compose

I think this could be an additional section in https://docs.dify.ai/getting-started/install-self-hosted/docker-compose, under `Upgrade Dify`

2024-05-25 04:50 UTC, crazywoola commented
Close for now.


> README might not be the best place for this, would you open a PR to put this in our docs instead? https://docs.dify.ai/getting-started/install-self-hosted/docker-compose
> 
> I think this could be an additional section in https://docs.dify.ai/getting-started/install-self-hosted/docker-compose, under `Upgrade Dify`

You can open a pr for this doc.

2024-05-25 04:50 UTC, closed without merging