Enabled Notion integration setup in Docker Compose Deployment
langgenius/dify pull request #3919
Opened 2024-04-27 07:47 UTC by kei-yamazaki

# Description

Among the two methods of self-hosting, the Local Source Code Start allows for the use of Notion Integration by creating a .env file. However, for the other method, Docker Compose Deployment, there was no way to set environment variables for Notion Integration, so it couldn't be used. Therefore, I made it possible to set the environment variables for Notion Integration in the docker-compose.yaml file.

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

I performed operational tests using the Internal type of Notion Integration.

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

2024-04-27 08:36 UTC, JohnJyong commented
It looks good in api service, but both api and worker services are needed, thanks @kei-yamazaki

2024-04-27 16:13 UTC, crazywoola approved these changes

2024-04-27 16:21 UTC, crazywoola requested changes
Missing worker configuration.

2024-04-28 05:40 UTC, kei-yamazaki commented
Thanks for the feedback.
I added the settings to worker.

2024-04-29 00:42 UTC, crazywoola approved these changes

2024-04-30 06:48 UTC, merged