🌟add docker-compose.yaml container_name.
langgenius/dify pull request #3930
Opened 2024-04-27 19:22 UTC by loks666

# Description

When I was helping others deploy, I found that none of the services in Docker-compose do specify container_name, which results in docker automatically assigning a container name when Docker-Compose starts the container, which is usually "service name -1". This will misunderstand many people and cause them to misunderstand the problem

## Type of Change

Please delete options that are not relevant.
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement

# How Has This Been Tested?

run "docker-compose up -d && docker ps -a"
You can view the service name without a suffix

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] `optional` I have added tests that prove my fix is effective or that my feature works
- [x] `optional` New and existing unit tests pass locally with my changes

2024-04-28 02:17 UTC, crazywoola requested changes
I would suggest using a prefix like `dify_api` to make sure it will not conflict with other named services.
And make sure you have changed all the yml files accordingly in the same folder.

2024-04-28 05:15 UTC, takatost requested changes
If you set `container_name`, it will prevent the service from setting multiple replicas, not recommended to do so;
If you want each container to have a custom prefix, you can deploy using `docker compose -p <your-project-name> up -d`.

2024-04-28 09:58 UTC, loks666 commented
This is also what puzzles me, why do other files have a specified container name, why not this file?

2024-04-28 12:24 UTC, takatost commented
> This is also what puzzles me, why do other files have a specified container name, why not this file?

Are you referring to the Milvus Docker Compose file? Because its services are stateful and cannot be deployed multiple replicas, so you need to set the `container_name`.

2024-04-28 17:21 UTC, loks666 commented
Yes, it's docker-compose.milvus.yaml. Now I'm confused what do you mean by creating a copy? Is there a need to create multiple apis? Or is it docker swarm?

2024-04-29 03:02 UTC, bowenliang123 commented
No significant improvements in usability and clarity were found in this PR.
It never bother me to have `docker_web_1`, `docker_api_1` and `docker_worker_1` container names by default.

Or could you summarize the changes and impact with expected containers in lis for before and after this PR ?

2024-04-30 05:00 UTC, takatost commented
I've closed this PR for now. Feel free to reach out if you have any questions.

2024-04-30 05:00 UTC, closed without merging