Add rerank model type for LocalAI provider
langgenius/dify pull request #3952
Opened 2024-04-28 09:53 UTC by thiner

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)
This PR fixes #3524 

## Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

First draft version, haven't gotten resources to test it.

- [ ] TODO

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

2024-04-29 03:42 UTC, takatost requested changes

2024-04-29 03:42 UTC, takatost commented on web/yarn.lock
Please remove irrelevant content. 😁

2024-05-08 15:58 UTC, thiner reviewed
lgtm

2024-05-08 15:58 UTC, thiner commented on web/yarn.lock
reverted

2024-05-11 03:29 UTC, takatost approved these changes
LGTM

2024-05-11 03:29 UTC, merged