Bedrock coher fix max length 2048
langgenius/dify pull request #4253
Opened 2024-05-10 06:48 UTC by kerlion

# Description

It includes 2 changes:
1. For Cohere, count the tokens as text length to avoid 2048 length limitation..
2. For others,  count  the tokens with tiktoken tokennizer, uses gpt-4 instead of gpt2.

Fixes #3942

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

 Test with text file with consecutive punctuation marks or long English words. It will failed with expected maxLength: 2048 before. Now it is fixed by counting the tokens as chars.

- [ ] TODO

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

2024-05-20 06:13 UTC, guchenhe requested changes

2024-05-20 06:13 UTC, guchenhe commented on api/core/model_runtime/model_providers/bedrock/text_embedding/text_embedding.py
> +    _enc = None
please define this in the `get_num_tokens` where its needed, instead of the class level

2024-05-29 11:16 UTC, crazywoola commented
@kerlion Please resolve the conversation above, we will merge it later.

2024-06-13 09:31 UTC, crazywoola approved these changes

2024-06-13 09:33 UTC, crazywoola commented
Hello please fix the conflicts :) dm on wechat if you finished this -> crazyphage

2024-06-19 05:24 UTC, takatost requested changes

2024-06-19 05:24 UTC, takatost commented on api/core/model_runtime/model_providers/bedrock/text_embedding/text_embedding.py
> +    _enc = None
When will the value of _enc change? Also, _enc is a class variable, not an instance variable, will there be any issues?

2024-07-09 15:07 UTC, crazywoola commented
Close for now. You can resolve those conflicts and open a new one.

2024-07-09 15:07 UTC, closed without merging