refactor: refactor the button component using `forwardRef`
langgenius/dify pull request #4379
Opened 2024-05-14 12:25 UTC by TinsFox

# Description

refactor the button component using `forwardRef`

The previous button component was disguised as a div, which would lose the original capabilities of HTML, such as form submission. This will prevent users from submitting when JavaScript capabilities are turned off. But when we follow web standards, we can bring a better experience

This submission includes two contents:
1. Use forwardRef to reconstruct the button component
2. Change the original `type` attribute to `variant`. Type is the original attribute of button. We should not modify it.
3. Removed `memo`. As a basic component, memo is not required
Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement

# How Has This Been Tested?

All button components should behave the same as before

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

2024-05-20 01:58 UTC, nite-knite requested changes

2024-05-20 01:58 UTC, nite-knite commented on web/app/components/base/button/index.tsx
> -      <Spinner loading={loading} className='!text-white !h-3 !w-3 !border-2 !ml-1' />
Loading state is missing in the refactored component

2024-05-20 02:21 UTC, TinsFox commented on web/app/components/base/button/index.tsx
> -      <Spinner loading={loading} className='!text-white !h-3 !w-3 !border-2 !ml-1' />
Added it back in commit [`fe05ccf` (#4379)](https://github.com/langgenius/dify/pull/4379/commits/fe05ccf335ffb59e573660678cd2e4d64937bc05)

2024-05-27 12:53 UTC, crazywoola commented
@TinsFox Hello there is a conflict in this pr.

2024-05-28 02:12 UTC, TinsFox commented
@crazywoola  All conflicts have been resolved.

2024-05-31 06:30 UTC, JzoNgKVO requested changes

2024-05-31 06:30 UTC, JzoNgKVO commented on web/app/components/base/button/index.tsx
> +      variant: 'primary',
```suggestion
      variant: 'default',
```
default variant should be 'default'

2024-05-31 06:37 UTC, JzoNgKVO commented
@TinsFox 
Compared to the feature `main`, following files should change the original `type` attribute to `variant`

app/components/tools/add-tool-modal/index.tsx
app/components/tools/add-tool-modal/tools.tsx
app/components/tools/provider/detail.tsx
app/components/tools/workflow-tool/index.tsx
app/components/tools/workflow-tool/confirm-modal/index.tsx
app/components/workflow/nodes/parameter-extractor/components/extract-parameter/update.tsx
app/(shareLayout)/webapp-signin/page.tsx

2024-05-31 08:49 UTC, TinsFox commented on web/app/components/base/button/index.tsx
> +      variant: 'primary',
ths!

2024-06-19 06:09 UTC, JzoNgKVO approved these changes

2024-06-19 06:12 UTC, nite-knite approved these changes

2024-06-19 06:13 UTC, merged