fix:start Celery with a Redis cluster not in the same slot (#4472)
langgenius/dify pull request #4478
Opened 2024-05-17 06:48 UTC by vicwang3

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

2024-05-19 13:07 UTC, bowenliang123 commented
Some questions for further investigation:
1. how the `global_keyprefix` config of celery helps to fix the slot problem in Redis cluster concepts.
2. What's `{celery_global_prefix}` in the config example? Any reference explanation for the usage ? Is that template holder in some way?

2024-05-20 10:32 UTC, binarx2 commented
The configuration option should be `result_backend_transport_options` ?

https://docs.celeryq.dev/en/stable/getting-started/backends-and-brokers/redis.html#global-keyprefix

2024-05-21 08:36 UTC, vicwang3 commented
> Some questions for further investigation:
> 
> 1. how the `global_keyprefix` config of celery helps to fix the slot problem in Redis cluster concepts.
> 2. What's `{celery_global_prefix}` in the config example? Any reference explanation for the usage ? Is that template holder in some way?

The root of the issue is that in Redis cluster mode, keys are distributed across different nodes, and the cluster requires that all keys involved in a specific operation must be located within the same slot since such operations are designed to be executed atomically on a single node.
Solution
Utilizing Redis’s hash tag feature when defining keys for the message queue can ensure that related keys are assigned to the same slot. Users can customize the hash tag CELERY_GLOBAL_PREFIX={celery_global_prefix} in the .env configuration. When operating on REDIS, CELERY_GLOBAL_PREFIX will automatically be used as a prefix. Redis will then assign keys with the same hash tag to the same SLOT.

2024-05-25 05:21 UTC, crazywoola commented
This one can be reviewed as well. 
https://github.com/langgenius/dify/pull/4520

2024-06-19 05:41 UTC, takatost requested changes

2024-06-19 05:41 UTC, takatost commented on .gitignore
> +!/api/.env
The .env file should be ignored.

2024-06-19 05:41 UTC, takatost commented on api/.env.example
> +CELERY_GLOBAL_PREFIX={celery_global_prefix}
CELERY_GLOBAL_PREFIX should be left blank by default to avoid affecting existing users

2024-06-19 05:41 UTC, takatost commented on api/config.py
> +        self.CELERY_GLOBAL_PREFIX = get_env("CELERY_GLOBAL_PREFIX")
The default configuration of `global_keyprefix` is an empty string '', please set the default value of CELERY_GLOBAL_PREFIX to an empty string in DEFAULTS of config.py.

2024-06-19 05:41 UTC, takatost commented on api/extensions/ext_celery.py
> +            'global_keyprefix': app.config["CELERY_GLOBAL_PREFIX"]
Carefully consider, suggest setting the `global_keyprefix` key here only when `CELERY_GLOBAL_PREFIX` is not empty.

2024-07-02 09:57 UTC, closed without merging