[seanguo] add support of amazon titan v2 and modify the price of amazon titan v1
langgenius/dify pull request #4643
Opened 2024-05-24 08:36 UTC by longzhihun

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

2024-05-24 12:27 UTC, crazywoola submitted a review, later dismissed

2024-05-24 13:07 UTC, guchenhe reviewed
original price seems correct - total price is calculated by multiplying token count, input price, and unit:
` total_amount = tokens * unit_price * price_config.unit`

2024-05-24 13:09 UTC, guchenhe requested changes
pricing should be

2024-05-24 13:09 UTC, guchenhe commented on api/core/model_runtime/model_providers/bedrock/text_embedding/amazon.titan-embed-text-v2.yaml
> +  input: '0.02'
```suggestion
  input: '0.00002'
--


<br class="Apple-interchange-newline">'
```

2024-05-24 13:09 UTC, guchenhe commented on api/core/model_runtime/model_providers/bedrock/text_embedding/amazon.titan-embed-text-v2.yaml
> +  unit: '0.000001'
```suggestion
  unit: '0.001'
```

2024-05-24 19:37 UTC, guchenhe requested changes

2024-05-24 19:37 UTC, guchenhe commented on api/core/model_runtime/model_providers/bedrock/text_embedding/amazon.titan-embed-text-v2.yaml
> +--
seem like there are some extra whitespace introduced by my suggestion, would you delete these as well? lgtm otherwise!

2024-05-26 08:28 UTC, longzhihun commented on api/core/model_runtime/model_providers/bedrock/text_embedding/amazon.titan-embed-text-v2.yaml
> +--
done, please have a look, could i have your wechat? maybe communicate easy with wechat.

2024-05-26 15:30 UTC, guchenhe commented
lgtm! thx

2024-05-26 15:30 UTC, merged