feat: support Latex
langgenius/dify pull request #5001
Opened 2024-06-06 09:04 UTC by ZuzooVn

# Description

Support Latex response from LLMs

## Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tested

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [x] `optional` I have made corresponding changes to the documentation 
- [x] `optional` I have added tests that prove my fix is effective or that my feature works
- [x] `optional` New and existing unit tests pass locally with my changes

2024-06-07 12:20 UTC, crazywoola requested changes

2024-06-07 12:20 UTC, crazywoola commented on web/app/components/base/markdown.tsx
> +export const preprocessLaTeX = (content: string) => {
```suggestion
const preprocessLaTeX = (content: string) => {
```

2024-06-07 12:20 UTC, crazywoola commented on web/app/components/base/markdown.tsx
> +  const latexContent = preprocessLaTeX(props.content)
```suggestion
  const latexContent = preprocessLaTeX(content)
```

2024-06-07 12:20 UTC, crazywoola commented on web/app/components/base/markdown.tsx
> +export const preprocessLaTeX = (content: string) => {
```TypeScript
const preprocessLaTeX = (content: string) => 
  content.replace(/\\\[(.*?)\\\]/gs, (_, equation) => `$$${equation}$$`)
         .replace(/\\\((.*?)\\\)/gs, (_, equation) => `$${equation}$`);
```
Guess this is simpler

2024-06-08 08:01 UTC, ZuzooVn commented
I updated the code based on the requested change.

2024-06-12 11:14 UTC, crazywoola commented
Please fix errors in CI. :)

2024-06-14 11:26 UTC, crazywoola commented
Do you have examples that can be used for tests.

2024-06-14 12:18 UTC, ZuzooVn commented
> Do you have examples that can be used for tests.

Just ask chatgpt like this: give me some equation example of latex equation

2024-06-18 02:43 UTC, crazywoola approved these changes

2024-06-18 02:43 UTC, merged