dalle3 add style consistency parameter
langgenius/dify pull request #5067
Opened 2024-06-11 03:38 UTC by charli117

# Description

dalle3 add style consistency parameter: seed id, Ensure consistency in series image generation

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

2024-06-11 06:02 UTC, takatost requested changes

2024-06-11 06:02 UTC, takatost commented on api/core/tools/provider/builtin/dalle/tools/dalle3.py
> +        result.append(self.create_text_message(f'\nGenerate image source to Seed ID: {seed_id}'))
Is this code necessary?

2024-06-11 06:06 UTC, charli117 commented on api/core/tools/provider/builtin/dalle/tools/dalle3.py
> +        result.append(self.create_text_message(f'\nGenerate image source to Seed ID: {seed_id}'))
@takatost necessary, to pass the seed id of the previous task, for example:
![dell3 图像一致性保持](https://github.com/langgenius/dify/assets/24435100/c599ad17-8e10-4954-b366-1ebc0b25b08d)

2024-06-12 00:26 UTC, crazywoola approved these changes

2024-06-12 03:30 UTC, crazywoola approved these changes

2024-06-12 04:13 UTC, takatost approved these changes
LGTM

2024-06-12 04:59 UTC, merged

2024-06-12 13:39 UTC, XiaoLey commented
![image](https://github.com/langgenius/dify/assets/46273173/d881bba3-43f8-4a93-8a8b-581ee61ca561)

## OpenAI Instruction: 

![image](https://github.com/langgenius/dify/assets/46273173/dcb90846-e913-4a48-a064-ddd738bf1f04)

![image](https://github.com/langgenius/dify/assets/46273173/17696620-c919-4676-bb62-b9ed0d61a76c)

Even though I haven't seen `seed` parameter in the official OpenAI instructions for `Create Image`, could you please verify it?