poetry docker
langgenius/dify pull request #5105
Opened 2024-06-12 08:20 UTC by bowenliang123

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

2024-06-13 15:08 UTC, bowenliang123 commented
It works.

<img width="1159" alt="image" src="https://github.com/langgenius/dify/assets/1935105/88e04c00-ed50-4cb1-adcf-70c528db3cbb">

2024-06-13 15:24 UTC, bowenliang123 commented
cc @takatost

2024-06-19 07:58 UTC, takatost requested changes
Can we push the API with the tag starting with "poetry-" to the image repository? (excluding the latest tag)
This way, we can use the built image to validate on both amd64 and arm64 hosts.

2024-06-19 15:06 UTC, bowenliang123 commented
> Can we push the API with the tag starting with "poetry-" to the image repository? (excluding the latest tag) This way, we can use the built image to validate on both amd64 and arm64 hosts.

Sorry that I failed to manage to do that. Getting the `DOCKERHUB_USER` and `DOCKERHUB_TOKEN` null from Github secrets.

I will suggest to have the poetry-based dockerfile in this PR , and do the image pushing in the follow-ups.

2024-06-19 16:07 UTC, bowenliang123 commented
https://github.com/milvus-io/milvus-lite/issues/137

2024-06-20 01:00 UTC, bowenliang123 commented
Remained blocking issue: `pymilvus` 2.4.x fails the dependencies installation on Linux arm64, as it requires `milvus-lite` which does not provide the prebuilt whl package for arm64 on Linux (referring to https://pypi.org/project/milvus-lite/2.4.7/#files).

Therefore, we may have to revert the PR #3795 ,  falling back to use `pymilvus` 2.3.x to avoid the blocker for applying Poery build system.

2024-06-21 02:58 UTC, bowenliang123 commented on .github/workflows/api-tests.yml
> +          poetry check -C api --lock
declaimer: the `--lock` option does not change the lockfile , and it only makes sure the lockfile exists.

2024-06-21 17:34 UTC, takatost approved these changes
LGTM

2024-06-21 17:34 UTC, merged

2024-06-21 17:38 UTC, bowenliang123 commented
Most credit for this PR goes to @takatost for helping with the validation and refactoring of a runnable version of GitHub workflow for building and pushing the docker images. Thanks.

2024-07-09 02:04 UTC, junjiejiangjjj commented
Milvus-lite 2.4.8 now supports poetry and arm64