Update README
langgenius/dify pull request #5131
Opened 2024-06-12 16:43 UTC by Winson-030

# Description

Add repository dify-kubernetes which can deploy with YAML file on Kubernetes

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Successfully deployed on local Kubernetes cluster

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

2024-06-13 08:36 UTC, crazywoola requested changes
Please add this to other languages as well :)

2024-06-14 03:17 UTC, LeoQuote commented
IMHO Kubernetes manifests can be generated with helm template easily.

helm is providing a more user-friendly interface to configure app, users can easily upgrade dify to new version without reviewing thousands of lines yaml manifests.

helm can reuse many existing helm chart for components like minio, postgresql, those are well-maintained and can be upgraded easily.

The raw k8s manifest would contain thousands of lines of code with just a few parameter that needs user attention, and most of them are shared like database url, redis url etc, you would have to change them all if you want to customize your configuration.

Thus I would discourage using raw manifests as it’s not easy to maintain, I think this is an issue must be considered before merging this pr.

2024-06-14 04:13 UTC, Winson-030 commented
> IMHO Kubernetes manifests can be generated with helm template easily.
> 
> helm is providing a more user-friendly interface to configure app, users can easily upgrade dify to new version without reviewing thousands of lines yaml manifests.
> 
> helm can reuse many existing helm chart for components like minio, postgresql, those are well-maintained and can be upgraded easily.
> 
> The raw k8s manifest would contain thousands of lines of code with just a few parameter that needs user attention, and most of them are shared like database url, redis url etc, you would have to change them all if you want to customize your configuration.
> 
> Thus I would discourage using raw manifests as it’s not easy to maintain, I think this is an issue must be considered before merging this pr.

I did agree with you for these senerios, and this is why there are 2 community driven helm charts already, but YAML file is still necessary and needed for users who are not familar with helm and users who want to dive into seperate components.

2024-06-14 11:51 UTC, crazywoola approved these changes

2024-06-14 11:53 UTC, merged