fix: add repo check for build-push.yml
langgenius/dify pull request #5141
Opened 2024-06-13 03:31 UTC by GOODBOY008

# Description

CI : build-push.yml need to check the repo brefore triggered.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

2024-06-13 08:33 UTC, crazywoola commented on .github/workflows/build-push.yml
> +    if: github.repository == 'langgenius/dify'
And. this should be an and condition `github.event.pull_request.draft == false && github.repository == 'langgenius/dify'`

2024-06-13 08:34 UTC, crazywoola requested changes
See comments

2024-06-14 03:26 UTC, GOODBOY008 commented on .github/workflows/build-push.yml
> +    if: github.repository == 'langgenius/dify'
@crazywoola Because this ci trigger condition is `push` and `release` without `pull-request` . So condition `github.event.pull_request.draft == false` is redundant.

2024-06-14 11:15 UTC, crazywoola approved these changes

2024-06-14 11:15 UTC, merged