feat: support opensearch approximate k-NN
langgenius/dify pull request #5322
Opened 2024-06-17 10:45 UTC by baojingyu

# Description

This PR introduces support for opensearch approximate k-NN feature, leveraging opensearch for vector retrieval and storage. It includes the integration of opensearch for approximate k-NN search and vector operations, enhancing search functionality to enable faster and more efficient retrieval of similar items.

## Type of Change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement

# How Has This Been Tested?

- [ ] Unit tests were conducted to validate the functionality of opensearch approximate k-NN and vector operations integration.
- [ ] The following tests cover the new features and integration: [Describe the tests here]
- [ ] Test Configuration Details: [Include any relevant details for test setup]

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat` (backend) and `cd web && npx lint-staged` (frontend) to appease the lint gods
- [ ] `optional` New and existing unit tests pass locally with my changes

2024-06-17 13:23 UTC, takatost requested changes, later dismissed

2024-06-17 13:23 UTC, takatost commented on api/config.py
> +        # OpenSearch 配置项
Pls make sure the comments are in English, thanks!

2024-06-17 13:23 UTC, takatost commented on api/core/rag/datasource/vdb/opensearch/opensearch_vector.py
> +        ssl_context.verify_mode = ssl.CERT_NONE  # 禁用证书验证
Pls make sure the comments are in English, thanks!

2024-06-17 13:23 UTC, takatost commented on api/core/rag/datasource/vdb/opensearch/opensearch_vector.py
> +                    Field.VECTOR.value: embeddings[i],  # 确保这里传递的是数组
Same here.

2024-06-17 13:48 UTC, JohnJyong commented
pls sync the requirements to` pyproject.toml` and `peotry.lock`

2024-06-18 01:37 UTC, baojingyu commented
> the

It has been modified as required, please review.

2024-06-19 04:42 UTC, JohnJyong approved these changes

2024-06-19 04:43 UTC, JohnJyong commented
LGTM

2024-06-19 04:44 UTC, merged