Got dify running on Mac 14.1.2 (23B92) with colima
langgenius/dify pull request #5337
Opened 2024-06-17 18:03 UTC by boxabirds

# Description

I ran into some problems getting dify to run on Mac Sonoma. 
## Permission denied errors with `docker-redis-` and `docker-db-1` that were solved by using docker volumes

db: `docker logs docker-db-1`

`chown: /var/lib/postgresql/data/pgdata: Permission denied`

redis: `docker logs docker-redis-1`

`permission denied`

## Connection refused when the console tried to connect to the port 5001 service

`docker logs docker-nginx-1`

```
2024/06/17 17:38:47 [error] 29#29: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: _, request: "GET /console/api/setup HTTP/1.1", upstream: "http://172.30.0.8:5001/console/api/setup", host: "localhost", referrer: "http://localhost/install"
```

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

the sign-in page successfully appeared and I was able to create an account and go to the app. 

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

# Environment
```
➜  docker git:(main) ✗ docker version
Client: Docker Engine - Community
 Version:           26.1.4
 API version:       1.45
 Go version:        go1.22.4
 Git commit:        5650f9b102
 Built:             Wed Jun  5 10:47:13 2024
 OS/Arch:           darwin/arm64
 Context:           colima

Server: Docker Engine - Community
 Engine:
  Version:          26.1.1
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.9
  Git commit:       ac2de55
  Built:            Tue Apr 30 11:48:47 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.31
  GitCommit:        e377cd56a71523140ca6ae87e30244719194a521
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

2024-06-18 02:46 UTC, crazywoola commented on docker/nginx/conf.d/default.conf
> -
It seems you have removed those lines, but these should be kept.

2024-06-18 03:32 UTC, boxabirds commented
Apologies yes how can they be added again?

On Tue, 18 Jun 2024 at 03:47, crazywoola ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In docker/nginx/conf.d/default.conf
> <https://github.com/langgenius/dify/pull/5337#discussion_r1643661577>:
>
> >      }
> -
>
> It seems you have removed those lines, but these should be kept.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/langgenius/dify/pull/5337#pullrequestreview-2124317560>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABD62LWN7MMYSLX7RXQEGTZH6NSXAVCNFSM6AAAAABJOPJUDWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCMRUGMYTONJWGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-06-18 04:20 UTC, crazywoola commented
I think you can  manually add those lines and push to the upstream again.

2024-06-18 05:23 UTC, takatost requested changes

2024-06-18 05:23 UTC, takatost commented on docker/docker-compose.yaml
> +  postgres_data:
Moving the volume directory will cause a Breaking change, please set the default directory to ./volumes for the specified directory.

2024-07-03 11:26 UTC, crazywoola commented
We have upgrade our docker-compose.yaml in v0.6.12. I guess this can be closed for now.

2024-07-03 11:26 UTC, closed without merging