wrong response when delete conversation by api
langgenius/dify pull request #5401
Opened 2024-06-19 11:13 UTC by chivalry1314

# Description

wrong response when delete conversation by api

Fixes #5400

## Type of Change

- [&#10004; ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

![image](https://github.com/langgenius/dify/assets/16643409/15f09013-6cc9-4806-9d2c-35fe5df313e3)
![image](https://github.com/langgenius/dify/assets/16643409/2b12b48f-a51e-4436-9038-94634fcf28dc)
![image](https://github.com/langgenius/dify/assets/16643409/66af3e32-0f93-4c2e-af35-bcf56ab93eab)

- [ ] TODO

# Suggested Checklist:

- [&#10004; ] I have performed a self-review of my own code
- [ &#10004;] I have commented my code, particularly in hard-to-understand areas
- [&#10004; ] My changes generate no new warnings
- [&#10004; ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [&#10004; ] `optional` I have made corresponding changes to the documentation 
- [&#10004; ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ &#10004;] `optional` New and existing unit tests pass locally with my changes

2024-06-19 11:24 UTC, crazywoola submitted a review, later dismissed

2024-06-19 12:47 UTC, takatost commented
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE
Returning a 204 status code is reasonable and compliant with the standards. You can refer to this specification link for more details.

2024-06-19 13:51 UTC, chivalry1314 commented
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE Returning a 204 status code is reasonable and compliant with the standards. You can refer to this specification link for more details.

but if I use 204 status code I cannot get the success message as the dify document says from the server like the first picture I offered. the status code 204 means no further information is to be supplied.

2024-06-19 18:49 UTC, takatost commented
> > https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE Returning a 204 status code is reasonable and compliant with the standards. You can refer to this specification link for more details.
> 
> 
> 
> but if I use 204 status code I cannot get the success message as the dify document says from the server like the first picture I offered. the status code 204 means no further information is to be supplied. 

This is correct, so the direction for the fix could be to remove the response content from the API implementation and documentation, while keeping the 204 status code. Thank you.

2024-06-20 15:13 UTC, crazywoola requested changes

2024-06-20 15:13 UTC, crazywoola commented on .github/workflows/build-push.yml
Please remain this file untouched in main branch.

2024-06-20 15:13 UTC, crazywoola commented on api/controllers/service_api/app/message.py
This is not related as well.

2024-07-04 06:03 UTC, takatost commented
> > https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE Returning a 204 status code is reasonable and compliant with the standards. You can refer to this specification link for more details.
> 
> but if I use 204 status code I cannot get the success message as the dify document says from the server like the first picture I offered. the status code 204 means no further information is to be supplied.

204 status code of means the execution was successful, so you can ignore the `success` message internal.

2024-07-04 06:03 UTC, takatost requested changes

2024-07-04 06:03 UTC, takatost commented on api/services/message_service.py
> +        for hismessage in history_messages:
Please remove this particular piece of logic

2024-07-04 06:03 UTC, takatost commented on api/controllers/service_api/app/message.py
> +        'message_tokens': fields.Integer,
The changes here are not in line with the topic of current PR, please create a new PR separately, thanks!

2024-07-04 06:03 UTC, takatost commented on .github/workflows/build-push.yml
> +    branches: [ main ]
Please restore this workflow to its original state.

2024-07-05 02:51 UTC, crazywoola commented
Please resolve those comments and reopen a pull request based on the main branch.

2024-07-05 02:51 UTC, closed without merging