Feat/mysql search tool
langgenius/dify pull request #5439
Opened 2024-06-20 09:33 UTC by dajianguo

# Description

a new tool for execute mysql sql or get the table struct

Fixes # (issue)

## Type of Change

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Yes,I have test.

- [ ] TODO

# Suggested Checklist:

- [√] I have performed a self-review of my own code
- [√ ] I have commented my code, particularly in hard-to-understand areas
- [√ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

2024-06-20 10:19 UTC, bowenliang123 commented on api/core/tools/provider/builtin/dbutil/dbutil.py
> +class WikiPediaProvider(BuiltinToolProviderController):
Fix the incorrect tool provider name.

2024-06-20 10:20 UTC, bowenliang123 commented on api/core/tools/provider/builtin/dbutil/dbutil.yaml
> +  tags: # 标签，用于前端展示
Remove all the comments.

2024-06-20 10:22 UTC, bowenliang123 requested changes
Hi, please make sure all the codes and configs are provided in English for general usage. Including the YAML configs, text messages sent, exception messages and comments.

2024-06-21 01:14 UTC, dajianguo commented
sorry, i wil be modify this error

2024-06-21 01:19 UTC, crazywoola commented on api/core/tools/provider/builtin/dbutil/tools/sqlutil.py
> +class SqlutilTool(BuiltinTool):
It should be SqlUtilTool

2024-06-21 01:21 UTC, crazywoola commented on api/core/tools/provider/builtin/dbutil/tools/use_db.py
> +class use_db():
You should use `Camel case` to define a class.

2024-06-21 01:21 UTC, crazywoola commented on api/core/tools/provider/builtin/dbutil/tools/use_db.py
> +    # def get_engine(self):
Remove codes if they are not needed.

2024-06-21 01:22 UTC, crazywoola commented on api/core/tools/provider/builtin/dbutil/tools/use_db.py
> +            # engine = self.get_engine()
Remove codes if they are not needed.

2024-06-21 01:22 UTC, crazywoola commented on api/core/tools/provider/builtin/dbutil/tools/use_db.py
> +        # engine = self.get_engine()
Remove codes if they are not needed.

2024-06-21 01:22 UTC, crazywoola commented on api/core/tools/provider/builtin/dbutil/tools/use_db.py
> +        # engine = self.get_engine()
Remove codes if they are not needed.

2024-06-21 01:22 UTC, crazywoola commented on api/core/tools/provider/builtin/dbutil/tools/use_db.py
> +        # engine = self.get_engine()
Remove codes if they are not needed.

2024-06-21 01:23 UTC, crazywoola commented on api/core/tools/provider/builtin/dbutil/tools/use_db.py
> +        # return [
Remove codes if they are not needed.

2024-06-21 01:23 UTC, crazywoola commented on api/core/tools/provider/builtin/dbutil/tools/use_db.py
> +        # engine = self.get_engine()
Remove codes if they are not needed.

2024-06-21 01:23 UTC, crazywoola commented on api/core/tools/provider/builtin/dbutil/tools/use_db.py
> +        print(fields)
Remove codes if they are not needed.

2024-06-21 01:23 UTC, crazywoola commented on api/core/tools/provider/builtin/dbutil/tools/use_db.py
> +        print("use_db.get_columns_dict.dic---------------------------------",dic)
Do not use print in the code.

2024-06-21 01:24 UTC, crazywoola commented on api/core/tools/provider/builtin/dbutil/tools/tablestructutil.py
> +            return self.create_text_message("请选择数据库类型")
All the messages should be translated or in English.

2024-06-21 01:24 UTC, crazywoola commented on api/core/tools/provider/builtin/dbutil/tools/tablestructutil.py
> +            return self.create_text_message("请填写数据库链接信息，例如：mysql+pymysql://admin:admin@localhost:13306/test")
All the messages should be translated or in English.

2024-06-21 01:24 UTC, crazywoola commented on api/core/tools/provider/builtin/dbutil/tools/tablestructutil.py
> +            return self.create_text_message("请填写表名")
All the messages should be translated or in English.

2024-06-21 01:24 UTC, crazywoola commented on api/core/tools/provider/builtin/dbutil/tools/tablestructutil.py
> +                "创建数据库链接异常. {}".format(e)
All the messages should be translated or in English.

2024-06-21 01:24 UTC, crazywoola commented on api/core/tools/provider/builtin/dbutil/tools/tablestructutil.py
> +                "执行sql异常. {}".format(e)
All the messages should be translated or in English.

2024-06-21 01:25 UTC, crazywoola commented on api/core/tools/provider/builtin/dbutil/_assets/icon.svg
This is an icon from another tool right? Please choose a different one.

2024-06-21 01:25 UTC, crazywoola requested changes
Please resolve comments :) And thanks for your contribution.

2024-06-21 03:16 UTC, dajianguo commented
I have corrected the review comments

2024-07-05 12:35 UTC, crazywoola commented
Please fix the CI as well

2024-07-12 12:20 UTC, crazywoola commented
Close for now.

2024-07-12 12:20 UTC, closed without merging