extract db configs
langgenius/dify pull request #5491
Opened 2024-06-21 14:14 UTC by bowenliang123

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

2024-06-21 14:52 UTC, bowenliang123 commented
cc @takatost @JohnJyong

2024-06-22 02:02 UTC, takatost requested changes

2024-06-22 02:02 UTC, takatost commented on api/config.py
>      'SQLALCHEMY_DATABASE_URI_SCHEME': 'postgresql',
Perhaps forget to delete this line?

2024-06-22 02:02 UTC, takatost commented on api/config.py
>          self.SQLALCHEMY_ECHO = get_bool_env('SQLALCHEMY_ECHO')
And this line too.

2024-06-22 02:05 UTC, bowenliang123 commented on api/config.py
>      'SQLALCHEMY_DATABASE_URI_SCHEME': 'postgresql',
Nice catch, thanks.

2024-06-22 02:05 UTC, bowenliang123 commented on api/config.py
>          self.SQLALCHEMY_ECHO = get_bool_env('SQLALCHEMY_ECHO')
Removed.

2024-06-22 02:12 UTC, takatost requested changes

2024-06-22 02:12 UTC, takatost commented on dify.iml
These two files below are shown in the wrong place.

2024-06-22 02:13 UTC, bowenliang123 commented on dify.iml
Already removed. Due to the confusion of peotry settings and IDEA module settings on my local machine.

2024-06-22 02:20 UTC, takatost approved these changes
LGTM

2024-06-22 02:29 UTC, merged