Add new tool: Spider
langgenius/dify pull request #5725
Opened 2024-06-28 16:11 UTC by WilliamEspegren

# Description

Add [Spider](https://spider.cloud/), the [fastest](https://github.com/spider-rs/spider/blob/main/benches/BENCHMARKS.md#benchmark-results) open source scraper & crawler that returns LLM-ready data.

Twitter: [@WilliamEspegren](https://x.com/WilliamEspegren)

## Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I have created a new workflow in the UI then tested it manually with all the different parameters.

![image](https://github.com/langgenius/dify/assets/131612909/6dc9c012-59bd-4dcb-a21b-f94f143ab915)

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

This PR was inspired by #3819

2024-07-02 14:17 UTC, WilliamEspegren commented
@bowenliang123 could you check this one out? Let me know if you want any changes or help otherwise :)

2024-07-08 10:11 UTC, takatost commented
Hi @WilliamEspegren, I tried out [Spider](https://spider.cloud/), but neither the SIGN IN nor REGISTER buttons are bringing up the login screen as expected. It's happening on both Chrome and Safari.

2024-07-08 10:13 UTC, WilliamEspegren commented
> Hi @WilliamEspegren, I tried out [Spider](https://spider.cloud/), but neither the SIGN IN nor REGISTER buttons are bringing up the login screen as expected. It's happening on both Chrome and Safari.

Hi @takatos! Thank you for mentioning this issue. Here is the link instead: https://spider.cloud/login

2024-07-13 16:09 UTC, WilliamEspegren commented
@crazywoola @takatost just checking the status on this, if you want any help just ping me :)

2024-07-17 23:56 UTC, takatost requested changes

2024-07-17 23:56 UTC, takatost commented on api/core/tools/provider/builtin/spider/spiderApp.py
> +        print(api_key)
Please remove the printing of api key

2024-07-18 06:25 UTC, WilliamEspegren commented on api/core/tools/provider/builtin/spider/spiderApp.py
> +        print(api_key)
Thank you for noticing this!

2024-07-18 06:29 UTC, takatost approved these changes
Thanks!!

2024-07-18 06:29 UTC, merged

2024-07-30 01:03 UTC, ivuai commented
@WilliamEspegren is this tool still working in latest version? because it doesn't work for me when I enter API key it gives me this error: argument of type 'NoneType' is not iterable

2024-07-30 07:08 UTC, WilliamEspegren commented
Hey @ivuai! How does your parameters look like, and what nodes are you using?

2024-07-30 17:07 UTC, ivuai commented
I don't use any node, I'm just simply trying to add API key in tools and I don't use any parameters. Here is the screenshot. 
![Capture987](https://github.com/user-attachments/assets/f586d93c-1617-45b9-a8b5-89dbca073ffd)

2024-07-30 20:39 UTC, WilliamEspegren commented
Thank you @ivuai! Weird, I will look and test it out tomorrow :)

2024-07-31 09:13 UTC, WilliamEspegren commented
@ivuai the API was somehow down. I have added error checks to display this more clearly if that ever happens again, thanks for mentioning this 👏