fix: node-title-is-overflow-in-checklist
langgenius/dify pull request #5870
Opened 2024-07-02 09:12 UTC by aixgeek

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

2024-07-02 09:13 UTC, aixgeek commented
![image](https://github.com/langgenius/dify/assets/9697715/24998ecd-df90-417f-bf7e-7f8582f148c0)

![image](https://github.com/langgenius/dify/assets/9697715/dde9cc3b-9771-4e83-8e65-291adf3c2994)

2024-07-02 13:40 UTC, crazywoola commented
Thanks for your contribution. Please open an issue before creating a PR or link to an existing issue, fix the errors in CI as well.

2024-07-03 01:47 UTC, aixgeek commented
#5900 Add issure @crazywoola

2024-07-03 01:53 UTC, crazywoola commented
Please resolve lint errors in the CI.

2024-07-03 08:43 UTC, aixgeek commented
> Please resolve lint errors in the CI.

done

2024-07-04 13:16 UTC, aixgeek commented
@iamjoel

2024-07-09 02:13 UTC, iamjoel requested changes
You should use 'grow' instead of 'w-[340px]' to increase flexibility.

2024-07-09 02:13 UTC, iamjoel commented on web/app/components/workflow/header/checklist.tsx
> +                            <span className='w-[340px] truncate'>
You should use 'grow' instead of 'w-[340px]' to increase flexibility.

2024-07-09 07:12 UTC, iamjoel approved these changes

2024-07-09 07:12 UTC, merged