Feat/delete file when clean document
langgenius/dify pull request #5882
Opened 2024-07-02 12:08 UTC by JohnJyong

# Description

delete file when document or dataset cleaned

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

2024-07-02 13:13 UTC, crazywoola requested changes, later dismissed

2024-07-02 13:13 UTC, crazywoola commented on api/services/dataset_service.py
> +        document_was_deleted.send(document.id, dataset_id=document.dataset_id,
Why do we need to send the task if the `file_id` is `None`

2024-07-02 13:13 UTC, crazywoola commented on api/tasks/clean_dataset_task.py
> +        # delete files
```
# delete files
if documents:
    for document in documents:
        try:
            if document.data_source_type == 'upload_file' and document.data_source_info:
                file_id = document.data_source_info_dict.get('upload_file_id')
                file = db.session.query(UploadFile).filter(
                    UploadFile.tenant_id == document.tenant_id,
                    UploadFile.id == file_id
                ).first()
                if file:
                    storage.delete(file.key)
                    db.session.delete(file)
        except Exception:
            continue
```

2024-07-04 05:57 UTC, takatost requested changes

2024-07-04 05:57 UTC, takatost commented on api/tasks/clean_document_task.py
> +def clean_document_task(document_id: str, dataset_id: str, doc_form: str, file_id: str):
file_id should be declared as Optional[str] = None

2024-07-04 05:57 UTC, takatost commented on api/tasks/clean_document_task.py
> +                storage.delete(file.key)
It is recommended to add a try-raise so that the main process is not interrupted if a file is deleted abnormally.

2024-07-15 11:54 UTC, crazywoola approved these changes

2024-07-15 11:57 UTC, merged