Removed fireclaw-py, fixed and improved fireclaw tool
langgenius/dify pull request #5896
Opened 2024-07-02 23:25 UTC by ahasasjeb

# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. Close issue syntax: `Fixes #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

Fixes 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A   Run docker,use firecrawl
- [ ] Test B

2024-07-02 23:27 UTC, ahasasjeb commented
#5897

2024-07-02 23:30 UTC, ahasasjeb commented
Fireclaw-py uses APGL license

2024-07-03 01:02 UTC, laipz8200 requested changes
I did a preliminary review of your code and found a few issues. Could you please address them first? Also, I would prefer if we could use type annotations in the method parameters.

2024-07-03 01:02 UTC, laipz8200 commented on api/core/tools/provider/builtin/firecrawl/firecrawl_appx.py
> +    def __init__(self, api_key=None, api_url=None):
There's no need to change the variable names; the original ones are more suitable.

2024-07-03 01:02 UTC, laipz8200 commented on api/core/tools/provider/builtin/firecrawl/firecrawl_appx.py
> +        if not self.api_key:
The self-hosted version doesn't require an API key. Making this change could cause errors.

2024-07-03 01:02 UTC, laipz8200 commented on api/core/tools/provider/builtin/firecrawl/tools/crawl.py
> -            params=options,
Where are we handling options now?

2024-07-03 01:02 UTC, laipz8200 commented on api/core/tools/provider/builtin/firecrawl/firecrawl_appx.py
> +        job_id = response['jobId']  # 确保使用正确的键名
Please avoid using non-English comments in the code.

2024-07-03 01:05 UTC, ahasasjeb commented
I forgot to make the changes. After running it successfully, I submitted it directly and will make the changes in three hours
---- Replied Message ----
From ***@***.***> Date 07/03/2024 09:03 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [langgenius/dify] Removed firecrawl-py, fixed and improved firecrawl tool (PR #5896) 
@laipz8200 requested changes on this pull request.
I did a preliminary review of your code and found a few issues. Could you please address them first? Also, I would prefer if we could use type annotations in the method parameters.
In api/core/tools/provider/builtin/firecrawl/firecrawl_appx.py:
> class FirecrawlApp: - def __init__(self, api_key=None, base_url=None): + def __init__(self, api_key=None, api_url=None): 
There's no need to change the variable names; the original ones are more suitable.
In api/core/tools/provider/builtin/firecrawl/firecrawl_appx.py:
> self.api_key = api_key - self.base_url = base_url or 'https://api.firecrawl.dev' - if self.api_key is None and self.base_url == 'https://api.firecrawl.dev': - raise ValueError('No API key provided') + if not self.api_key: 
The self-hosted version doesn't require an API key. Making this change could cause errors.
In api/core/tools/provider/builtin/firecrawl/tools/crawl.py:
> crawl_result = app.crawl_url( url=tool_parameters['url'], - params=options, 
Where are we handling options now?
In api/core/tools/provider/builtin/firecrawl/firecrawl_appx.py:
> - def _prepare_headers(self): - return { - 'Content-Type': 'application/json', - 'Authorization': f'Bearer {self.api_key}' - } - - def _post_request(self, url, data, headers): - return requests.post(url, headers=headers, json=data) + def crawl_url(self, url, wait=False, poll_interval=5, idempotency_key=None, **kwargs): + endpoint = f'{self.api_url}/v0/crawl' + headers = self._prepare_headers(idempotency_key) + data = {'url': url, **kwargs} + response = self._request('POST', endpoint, data, headers) + job_id = response['jobId'] # 确保使用正确的键名 
Please avoid using non-English comments in the code.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-07-03 01:29 UTC, ahasasjeb commented on api/core/tools/provider/builtin/firecrawl/firecrawl_appx.py
> +        if not self.api_key:
YAML requires mandatory filling

2024-07-04 08:39 UTC, crazywoola commented
Please resolve this comments by clicking those buttons.

2024-07-04 08:51 UTC, ahasasjeb commented
ok

2024-07-05 07:20 UTC, laipz8200 requested changes

2024-07-05 07:20 UTC, laipz8200 commented on api/core/tools/provider/builtin/firecrawl/firecrawl_appx.py
> +        job_id = response['jobId']
Since the return value of `self._request` may be `None`, this could potentially lead to an exception.

2024-07-05 07:20 UTC, laipz8200 commented on api/core/tools/provider/builtin/firecrawl/firecrawl_appx.py
> +                if response.status_code == 502 and i < retries - 1:
If the `requests.request` method fails, the `response` can be `None`. Attempting to access the `status_code` in this case may cause another exception.

2024-07-05 07:20 UTC, laipz8200 commented on api/core/tools/provider/builtin/firecrawl/firecrawl_appx.py
> +            if status['status'] == 'completed':
ditto

2024-07-05 07:20 UTC, laipz8200 commented on api/core/tools/provider/builtin/firecrawl/firecrawl_appx.py
> +            elif status['status'] == 'failed':
ditto

2024-07-05 10:01 UTC, laipz8200 submitted a review, later dismissed
LGTM

2024-07-05 10:04 UTC, laipz8200 approved these changes

2024-07-05 10:04 UTC, merged