fix: when http request body is raw or json, if there are line breaks and double quotes, the request will fail
langgenius/dify pull request #6135
Opened 2024-07-10 05:32 UTC by hellof20

# Description

My workflow is to send the output of the large model to an external API via http request node，when http request body is raw or json, if there are line breaks and double quotes, the request will fail.

<img width="522" alt="image" src="https://github.com/langgenius/dify/assets/8756642/d344b562-7136-405f-8d16-9d92b92ca91c">

<img width="342" alt="image" src="https://github.com/langgenius/dify/assets/8756642/4926203f-169b-40c8-8152-787d441ac94f">

I found that the error was caused by multi-line text or double quotes
<img width="524" alt="image" src="https://github.com/langgenius/dify/assets/8756642/6645cdee-3be5-4f79-9bee-f72a2ffea539">

# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

Fixes 

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

2024-07-15 11:26 UTC, hellof20 commented
hello @iamjoel , could you help to review this?

2024-07-15 11:33 UTC, iamjoel commented
@Yeuoly Please help to review it.

2024-07-15 12:33 UTC, Yeuoly requested changes
this trick should be moved to http_request_executor.py instead of variable_template_parser as it will alter many originally normal code logics, such as when it's not in an http node, but in an LLM node

2024-07-16 00:38 UTC, hellof20 commented
@Yeuoly I tried to modify it in http_request_executor.py, but when the request parameter is raw or json, it is multi-line,
```
{
"msg_type":"text",
"content":{
"text": " {"xxx"}
}
}
```
If it is replaced with '\n', it will also cause the http request parameter format to be incorrect and cause an error.
In addition, I found that there was no problem with the LLM node output, and the problem occurred after being processed by variable_template_parser, so I modified variable_template_parser

2024-07-16 03:21 UTC, Yeuoly commented
> @Yeuoly I tried to modify it in http_request_executor.py, but when the request parameter is raw or json, it is multi-line,
> 
> ```
> {
> "msg_type":"text",
> "content":{
> "text": " {"xxx"}
> }
> }
> ```
> 
> If it is replaced with '\n', it will also cause the http request parameter format to be incorrect and cause an error. In addition, I found that there was no problem with the LLM node output, and the problem occurred after being processed by variable_template_parser, so I modified variable_template_parser

Actually, I guess what we need is escaping quotes in plaintext which is a JSON field, I dig into the code and found line breaks are not handled correctly here https://github.com/langgenius/dify/blob/main/api/core/workflow/nodes/http_request/http_executor.py#L347
the original logic is checking if it's already a valid JSON string, if so, escape quotes, otherwise do nothing, maybe you can optimize this.

2024-08-05 04:52 UTC, closed without merging

2024-08-05 06:53 UTC, onevcat commented
We are also facing the same problem and seems there is no way to create a correct JSON request for API use. It becomes a blocker for our use of Dify.

Is there any workaround or plan to fix?