Pass the inputs values using `difyChatbotConfig`
langgenius/dify pull request #6376
Opened 2024-07-17 08:09 UTC by yoyocircle

# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

> Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. Close issue syntax: `Fixes #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

Adding the key `inputs` to `difyChatbotConfig` and make it fill the inputs when initializing the chatbot.
related issues: #5575

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-07-17 08:53 UTC, crazywoola commented
Please notice it will conflict with https://github.com/langgenius/dify/pull/6360 on  `embed.min.js`. It needs to be rebuilt again.

2024-07-17 09:37 UTC, yoyocircle commented
> Please notice it will conflict with #6360 on `embed.min.js`. It needs to be rebuilt again.

Hello @crazywoola, I will try to solve the conflict after #6360 is merged into main.

2024-07-17 12:53 UTC, crazywoola commented
Merged, please fix the lint errors as well.

2024-07-18 02:20 UTC, yoyocircle commented
Hi @crazywoola, the changes should be done, and also add another feature to compress the strings.

2024-07-18 03:23 UTC, crazywoola requested changes

2024-07-18 03:23 UTC, crazywoola commented on web/app/components/base/chat/embedded-chatbot/hooks.tsx
> +    async function decodeBase64AndDecompress(base64String) {
Suggest to move this util function to `web/app/components/base/chat/utils`

2024-07-18 05:28 UTC, yoyocircle commented
Hi @crazywoola, the functions were moved. And also validate the values when the inputs type is number or select.

2024-07-18 07:06 UTC, yoyocircle commented
> Can you add my wechat: crazyphage

sure, will add you tonight.

2024-07-18 13:34 UTC, crazywoola commented on web/app/components/base/chat/utils.ts
> +async function decodeBase64AndDecompress(base64String) {
```suggestion
async function decodeBase64AndDecompress(base64String: string) {
```

2024-07-18 13:35 UTC, crazywoola reviewed
text-input is not working, the rest of types are working for me.

2024-07-18 13:47 UTC, yoyocircle commented
> text-input is not working, the rest of types are working for me.

This is fixed. 
And added the length check for text-input and paragraph.

2024-07-18 13:54 UTC, crazywoola approved these changes

2024-07-18 13:54 UTC, merged

2024-07-24 05:53 UTC, xbduck commented
inputs: {
        // 键是变量名
        // 例如：
        name: "NAME",
      },
配置的name对应的默认值 页面上没有读取到

2024-07-26 07:21 UTC, Amandine95 commented
is the key in inputs same with the params  name set in start node ?

2024-07-26 07:21 UTC, Amandine95 commented
> inputs: { // 键是变量名 // 例如： name: "NAME", }, 配置的name对应的默认值 页面上没有读取到


问题结局了吗？

2024-07-26 07:21 UTC, xbduck commented
自动回复：您好，你的邮件已经收到，我会尽快拜读，祝你天天开心，万事如意！

2025-02-26 06:17 UTC, biglazybug commented
> > inputs: { // 键是变量名 // 例如： name: "NAME", }, 配置的name对应的默认值 页面上没有读取到
> 
> 问题如何解决的？

问题解决了吗

2025-02-26 06:18 UTC, xbduck commented
自动回复：您好，你的邮件已经收到，我会尽快拜读，祝你天天开心，万事如意！

2025-03-13 08:15 UTC, wumingyu12 commented
具体在工作流中怎么用这个input 里面的变量的

2025-03-13 08:16 UTC, xbduck commented
自动回复：您好，你的邮件已经收到，我会尽快拜读，祝你天天开心，万事如意！