Fix the issue dify-issues-6389
langgenius/dify pull request #6391
Opened 2024-07-17 12:09 UTC by JinCheng666

https://github.com/langgenius/dify/issues/6389

# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. Close issue syntax: `Fixes #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

Fixes 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-07-17 13:03 UTC, crazywoola requested changes

2024-07-17 13:03 UTC, crazywoola commented on api/core/model_runtime/model_providers/openai_api_compatible/text_embedding/text_embedding.py
> +                'input': ['ping'],
According to this doc https://platform.openai.com/docs/api-reference/embeddings/create#embeddings-create-input
It should be a string or an array.

2024-07-17 13:04 UTC, takatost commented
<img width="563" alt="image" src="https://github.com/user-attachments/assets/621d5f42-26c7-4157-a604-32121635d0e2">
https://platform.openai.com/docs/api-reference/embeddings/create#embeddings-create-input
Hi @JinCheng666, string and array are both allowed types.

2024-07-18 00:00 UTC, JinCheng666 commented
> <img alt="image" width="563" src="https://private-user-images.githubusercontent.com/5485478/349509041-621d5f42-26c7-4157-a604-32121635d0e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNjA4OTQsIm5iZiI6MTcyMTI2MDU5NCwicGF0aCI6Ii81NDg1NDc4LzM0OTUwOTA0MS02MjFkNWY0Mi0yNmM3LTQxNTctYTYwNC0zMjEyMTYzNWQwZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTdUMjM1NjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDljNTI1M2MxNWJjNjU4NDEwMjgwNTYzNDk5MDBiYmI4YjU1NmY2NWZhNjc3NGMyOGE3YWM1ZjQxYjViYjVlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.B8lfFO-0p9SihX7Ce4wPr2S_goo3QaGBD2U6OuR-Ymg"> https://platform.openai.com/docs/api-reference/embeddings/create#embeddings-create-input
> Hi @JinCheng666, string and array are both allowed types.

Thank you for your reply and guidance, but I don't know enough about the interface. Thank you again

2024-07-18 00:00 UTC, closed without merging