Fix ScrapeTool parameter validation errors
langgenius/dify pull request #6427
Opened 2024-07-18 10:08 UTC by likenamehaojie

Changed placeholders to I18nObject instances to pass validation checks.

# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description
Fix validation error for ScrapeTool parameters

The previous implementation contained invalid placeholders for the
ScrapeTool parameters, causing validation errors during runtime.
This was due to the placeholders not being instances of I18nObject.

To resolve this, I've updated the placeholders to use I18nObject instances,
providing correct translations for 'zh_Hans', 'pt_BR', and 'en_US'.
This ensures that the tool's parameters are now properly validated.

Related issue: #123
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. Close issue syntax: `Fixes #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

Fixes 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency upgrade

2024-07-18 10:31 UTC, crazywoola requested changes

2024-07-18 10:31 UTC, crazywoola commented on api/pyproject.toml
This is unrelated to this pr, please remain this file and poetry.lock file untouched.

2024-07-18 11:32 UTC, laipz8200 commented on api/pyproject.toml
> +[[tool.poetry.source]]
Please do not add a third-party source.

2024-07-18 11:34 UTC, laipz8200 requested changes

2024-07-18 11:34 UTC, laipz8200 commented on api/core/tools/provider/builtin/spider/tools/scraper_crawler.yaml
> -    placeholder: /blog/*, /about
You can leave this placeholder, but please use the same i18n format as the label.

2024-07-18 11:34 UTC, laipz8200 commented on api/core/tools/provider/builtin/spider/tools/scraper_crawler.yaml
> -    placeholder: /blog/*, /about
ditto

2024-07-19 05:56 UTC, laipz8200 commented on .vscode/launch.json
> -            "python": "${workspaceFolder}/api/.venv/bin/python",
Please refrain from modifying our config file.

2024-07-19 05:56 UTC, laipz8200 commented on .vscode/launch.json
> -            "python": "${workspaceFolder}/api/.venv/bin/python",
ditto

2024-08-05 04:52 UTC, closed without merging

2026-01-14 16:16 UTC, likenamehaojie commented
我就改了一行代码，怎么多出这么多？watercrawl不能使用