bump dify-sandbox from 0.2.1 to 0.2.3
langgenius/dify pull request #6738
Opened 2024-07-27 12:52 UTC by jerryleooo

# Description

- Fix https://github.com/langgenius/dify/issues/4463
- Fix https://github.com/langgenius/dify/issues/6601

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

2024-07-27 12:55 UTC, jerryleooo commented
@crazywoola

2024-07-29 05:18 UTC, Yeuoly commented
Pls fix the CI errors

2024-07-29 10:31 UTC, takatost requested changes
The problem with CI is due to sandbox startup timeout, you can add a tcp continuous listen, e.g. "nc -z 127.0.0.1 8194" until the connection is successful, then you can perform the next step.

2024-07-29 10:31 UTC, takatost commented on docker/docker-compose.middleware.yaml
> +    image: langgenius/dify-sandbox:0.2.3
Recommend upgrading to the latest version 0.2.4.

2024-07-29 10:47 UTC, jerryleooo commented on docker/docker-compose.middleware.yaml
> +    image: langgenius/dify-sandbox:0.2.3
done

2024-08-21 06:22 UTC, closed without merging