Add support for i18n Persian language (fa-IR)
langgenius/dify pull request #6976
Opened 2024-08-05 14:01 UTC by sadeghtkd

I have used LLMs translation to translate from English to Farsi.
Then, I manually checked each translation for errors or missing.

Type of Change
 New feature (non-breaking change which adds functionality)

2024-08-06 02:10 UTC, crazywoola requested changes

2024-08-06 02:10 UTC, crazywoola commented on web/yarn.lock
Please leave this file untouched.

2024-08-06 19:03 UTC, asrguru20 commented
دمت گرم صادق جان

2024-08-07 01:01 UTC, crazywoola commented on web/yarn.lock
Hello, you need to revert the changes in `yarn.lock` because it's not related to this PR. Not `delete` this file. :)

2024-08-07 05:42 UTC, closed without merging