Web app now supports SSO config
langgenius/dify pull request #7137
Opened 2024-08-09 07:14 UTC by douxc

# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

you can set enable/disable sso feature for web app at setting modal

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

2024-08-14 07:52 UTC, GarfieldDai commented on web/i18n/zh-Hans/app-overview.ts
> +          label: '认证设置',
单点登录认证

2024-08-14 07:54 UTC, GarfieldDai commented on web/i18n/en-US/app-overview.ts
> +          title: 'Web Application SSO',
WebApp SSO

2024-08-14 07:55 UTC, GarfieldDai commented on web/i18n/zh-Hans/app-overview.ts
> +          title: 'WebApp 认证',
WebApp SSO 认证

2024-08-14 07:57 UTC, GarfieldDai commented on web/i18n/zh-Hans/app-overview.ts
> +          tooltip: '联系管理员以开启 Web 应用的 SSO 认证',
联系管理员以开启 WebApp SSO 认证

2024-08-14 07:57 UTC, GarfieldDai commented on web/i18n/en-US/app-overview.ts
> +          tooltip: 'Contact the administrator to enable Web Application SSO',
Contact the administrator to enable WebApp SSO

2024-08-14 08:02 UTC, GarfieldDai commented on web/i18n/en-US/app-overview.ts
> +          description: 'All users are required to login with SSO before using web application',
All users are required to login with SSO before using WebApp

2024-08-14 08:09 UTC, GarfieldDai commented on web/i18n/en-US/app-overview.ts
> +          tooltip: 'Contact the administrator to enable Web Application SSO',
Contact the administrator to enable WebApp SSO

2024-08-14 08:09 UTC, GarfieldDai commented on web/i18n/zh-Hans/app-overview.ts
> +          description: '启用后，所有用户都需要先认证后才能访问',
启用后，所有用户都需要先进行 SSO 认证才能访问

2024-08-15 13:00 UTC, crazywoola requested changes
See comments

2024-08-15 13:00 UTC, crazywoola commented on web/app/(commonLayout)/app/(appDetailLayout)/[appId]/overview/cardView.tsx
> +      if (systemFeatures.enable_web_sso_switch_component) {
Avoid using nested promises in async function, you should use `try catch` to handle the exceptions as well.

2024-08-15 13:00 UTC, crazywoola commented on web/app/components/app/overview/settings/index.tsx
> +      enable_sso: inputInfo.enable_sso!,
```
{
    title,
    desc: description,
    chatColorTheme: chat_color_theme,
    chatColorThemeInverted: chat_color_theme_inverted,
    copyright,
    privacyPolicy: privacy_policy,
    customDisclaimer: custom_disclaimer,
    show_workflow_steps,
    enable_sso: appInfo.enable_sso,
  }
```
This should have a type, and make `enable_sso` optional.

2024-08-15 13:00 UTC, crazywoola commented on web/app/components/base/tooltip-plus/index.tsx
> +      open={disabled ? false : open}
```suggestion
      open={!disabled && open}
```

2024-08-15 13:00 UTC, crazywoola commented on web/i18n/en-US/app-overview.ts
> +          label: 'SSO ENFORCEMENT',
This is a wrong for `'单点登录认证'`

2024-08-15 13:00 UTC, crazywoola commented on web/service/apps.ts
> +export const updateAppSSO = async ({ id, enabled }: { id: string;enabled: boolean }) => {
```suggestion
export const updateAppSSO = async ({ id, enabled }: { id: string; enabled: boolean }) => {
```

2024-08-19 10:13 UTC, crazywoola approved these changes
LGTM

2024-08-25 09:48 UTC, GarfieldDai approved these changes
LGTM

2024-08-25 10:47 UTC, merged