Update PerfXCloud Model List
langgenius/dify pull request #7212
Opened 2024-08-13 03:33 UTC by BingGeX

Add Llama-3.1-405B,Llama-3.1-8B,Llama-3-70B,Llama-3-8B,Qwen2-72B,deepseek-v2-chat,deepseek-v2-lite-chat,Llama3-Chinese_v2,chatglm3-6b,BAAI-bge-large-en-v1.5,BAAI-bge-large-zh-v1.5 model; Update Qwen2-72B-Instruct-GPTQ-Int4,Qwen2-7B,Qwen1.5-72B-Chat-GPTQ-Int4,Qwen1.5-7B model; Delete Qwen-14B-Chat-Int4,Qwen1.5-110B-Chat-GPTQ-Int4;

# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

PerXCloud Model need update.

Fixes 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

The project is successfully run and the PerfXCloud vendor is created. The new model is included in the model list.

2024-08-13 04:10 UTC, crazywoola requested changes
In order to make legacy workflows work as expected, please add the new yaml file instead of renaming model name in it. 
And you need to mark legacy yaml with `deprecated: true`

See examples here: https://github.com/langgenius/dify/blob/5c258e212ca7459119ecbf3f490e293930c85458/api/core/model_runtime/model_providers/anthropic/llm/claude-instant-1.yaml

2024-08-15 02:40 UTC, BingGeX commented
@crazywoola 
The previous model yaml file has been restored and `deprecated: true` added.

2024-08-15 10:24 UTC, BingGeX reviewed
The previous model yaml file has been restored and `deprecated: true` added.

2024-08-15 11:37 UTC, crazywoola approved these changes

2024-08-15 11:42 UTC, merged