feat: Sort conversations by updated_at desc
langgenius/dify pull request #7348
Opened 2024-08-16 07:44 UTC by KinWang130

# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] I have performed a self-review of my own code
- [x] I ran `dev/pr`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description
In the process of using dify for conversations, the historical conversation records are always sorted in descending order according to the time of session creation. Normally, they should be sorted according to the latest time of conversation messages.
My optimization is to modify the updated_at of the conversation during the conversation, and sort the conversation list in descending order based on the updated_at. This way, users can see the latest list of session messages.

Fixes https://github.com/langgenius/dify/issues/7338

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Initiate a new conversation, with the new conversation at the forefront
- [x] The conversation list is sorted based on the latest time of the conversation content

2024-08-16 15:01 UTC, laipz8200 commented
I think sorting by creation time is reasonable because it ensures the relative order of items in the list remains unchanged. Do you have a more compelling argument for sorting by update time?

2024-08-17 01:07 UTC, laipz8200 commented
> > I think sorting by creation time is reasonable because it ensures the relative order of items in the list remains unchanged. Do you have a more compelling argument for sorting by update time?
> 
> Of course, sorting by creation time can ensure that the relative order remains unchanged, but in most conversational applications such as GPT, WeChat, Telegram, etc., conversations are always sorted by the latest conversation messages. My optimization reasons are as follows:
> 
>     1. Updated_at is always unchanged. When a new message is generated in a conversation or the conversation name is modified, updated_at should be updated, otherwise it is meaningless
> 
>     2. Each conversation may generate a theme, and when users generate new messages in each conversation, I believe they want the conversation to be prioritized, which is very user-friendly
>        What's your opinion?

I think it would be great to support both options. How about we add a `sort_by` parameter to the API? That way, we could pass `sort_by=-updated_at` to sort by updated_at in descending order.

2024-08-17 02:10 UTC, leslie2046 commented
+1 
https://github.com/langgenius/dify/issues/7338
I think the conversation list on the left side of the webui should be sorted by 'updated_at'
And the log list in the console should also be sorted by updated_at. When we check the logs every day, we hope to only look at the current day's logs without having to repeatedly review the sessions we have already seen yesterday.

2024-08-19 04:39 UTC, laipz8200 commented
Hi @KinWang130! Apologies for the lack of clarity earlier. We would like to support the option to specify the sorting method in the web service API. Instead of directly changing the current sorting method, we aim to allow users to choose their preferred sorting method by adding a button in the frontend. Would you be willing to implement this feature?

2024-08-19 08:31 UTC, laipz8200 commented
@KinWang130 Thank you very much for your contribution! We plan to add sorting options on the logs page and use the default order on the chat page. Due to the need for design and front-end development, the merging of this PR might be slightly delayed.

Additionally, please check the CI errors.

2024-08-19 08:41 UTC, laipz8200 commented
You can run `dev/reformat` to fix the most lint errors automatically.

2024-08-19 08:42 UTC, leslie2046 commented
@laipz8200 
https://github.com/langgenius/dify/issues/7338
My issue will be resolved  if we can sort by create_at or update_at in logs page ,thank you!

2024-08-19 08:56 UTC, laipz8200 requested changes

2024-08-19 08:56 UTC, laipz8200 commented on api/services/conversation_service.py
> +            # 根据排序方式构建过滤条件
ditto

2024-08-19 08:56 UTC, laipz8200 commented on api/services/conversation_service.py
> +            # 构建剩余数量查询的过滤条件
ditto

2024-08-19 08:56 UTC, laipz8200 commented on api/services/conversation_service.py
> +        # 应用排序
ditto

2024-08-19 08:56 UTC, laipz8200 commented on api/services/conversation_service.py
> +        # 定义排序字段和方向
Please do not use Chinese comments in the code.

2024-08-19 12:38 UTC, crazywoola approved these changes, later dismissed
@laipz8200

2024-08-20 09:55 UTC, laipz8200 approved these changes
Thanks for your contribution!

2024-08-20 09:55 UTC, merged