Fix error when score_threshold is None for MyScale vector database
langgenius/dify pull request #7640
Opened 2024-08-26 05:32 UTC by lqhl

# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. Close issue syntax: `Fixes #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

Fixes #7638

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-08-26 08:42 UTC, laipz8200 requested changes

2024-08-26 08:42 UTC, laipz8200 commented on api/core/rag/datasource/vdb/myscale/myscale_vector.py
> +        score_threshold = kwargs.get('score_threshold') if kwargs.get('score_threshold') else 0.0
You can use `or` to make this code more readable and clear.

```python
score_threshold = kwargs.get('score_threshold') or 0.0
```

2024-08-26 09:12 UTC, crazywoola commented on api/core/rag/datasource/vdb/myscale/myscale_vector.py
> +        score_threshold = kwargs.get('score_threshold') if kwargs.get('score_threshold') else 0.0
```suggestion
        core_threshold = kwargs.get('score_threshold') or 0.0
```

2024-08-26 09:12 UTC, crazywoola approved these changes, later dismissed

2024-08-27 01:47 UTC, crazywoola approved these changes

2024-08-27 01:47 UTC, merged