feat: add gpt-4o-2024-08-06 and json_schema for azure openAI service
langgenius/dify pull request #7648
Opened 2024-08-26 07:54 UTC by hjlarry

# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Fixes https://github.com/langgenius/dify/issues/7636

1. add `gpt-4o-2024-08-06` model
2. support `json_schema` for `gpt-4o-2024-08-06` and `gpt-4o-mini-2024-07-18`

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

**NOT TEST**

I haven't got an azure key,  please help to test it, thanks!  @liaopen123 @crazywoola

2024-09-04 13:56 UTC, crazywoola approved these changes

2024-09-04 13:56 UTC, merged

2024-09-11 20:10 UTC, KevinHuerta26 requested changes

2024-09-11 20:10 UTC, KevinHuerta26 commented on api/core/model_runtime/model_providers/azure_openai/llm/llm.py
>          response_format = model_parameters.get("response_format")
Moto g 72

2024-09-11 20:10 UTC, KevinHuerta26 commented on api/core/model_runtime/model_providers/azure_openai/llm/llm.py
>          if response_format:
5515689829

2024-09-11 20:11 UTC, KevinHuerta26 commented on api/core/model_runtime/model_providers/azure_openai/llm/llm.py
> +import json
dea6212390e613064d0771df37177a2c08ea14af