bug: fix http timeout configs ignored by HttpRequestNode
langgenius/dify pull request #7762
Opened 2024-08-28 10:15 UTC by bowenliang123

# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

- the `min` operator causes the explicitly set http timeout configs are ignored
- replace `min` by using `conint(ge=)` to check http timeouts minimum

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-08-28 10:30 UTC, bowenliang123 commented on api/configs/feature/__init__.py
>          default=600,
Considering the http timeouts mainly used for code exectuion via `ssrf`, the current default value `600` is way to high for practice. 

@Yeuoly Could you confirm that `ssrf` service and caller uses this config via `httpx` in the unit of seconds?
@laipz8200 How about lower the default value to 1/10 to 60 seconds?

2024-08-29 07:01 UTC, laipz8200 requested changes

2024-08-29 07:01 UTC, laipz8200 commented on api/configs/feature/__init__.py
>          default=600,
The default values for the timeout arguments could be:

- Connect: 10 seconds
- Read: 60 seconds
- Write: 20 seconds

2024-08-29 07:01 UTC, laipz8200 commented on api/configs/feature/__init__.py
> +    HTTP_REQUEST_MAX_WRITE_TIMEOUT: conint(ge=10) = Field(
Please avoid using `conint` and instead set `ge` in `Field`, `conint` will be deprecated in Pydantic 3.0.

2024-08-29 12:37 UTC, bowenliang123 commented on api/configs/feature/__init__.py
> +    HTTP_REQUEST_MAX_WRITE_TIMEOUT: conint(ge=10) = Field(
Resolved. Change to used `Annotated[int, Field(ge=10)]` , as suggested in official docs (https://docs.pydantic.dev/latest/api/types/#pydantic.types.conint). Thanks for the reminder.

2024-08-30 11:08 UTC, laipz8200 approved these changes
LGTM

2024-08-30 11:09 UTC, merged