feat: support more model types and builtin tools on aws/sagemaker
langgenius/dify pull request #8061
Opened 2024-09-06 10:00 UTC by ybalbert001

# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. Close issue syntax: `Fixes #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

Fixes 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-09-06 14:03 UTC, crazywoola requested changes
TTS is working for me.

2024-09-06 14:03 UTC, crazywoola commented on api/core/model_runtime/model_providers/sagemaker/llm/llm.py
> +    根据给定的模型名称和端点名称，对消息进行推理。
All comments should be in English

2024-09-06 14:03 UTC, crazywoola commented on api/core/model_runtime/model_providers/sagemaker/llm/llm.py
> +        # assistant_message = resp.choices[0].message
Remove commented code here.

2024-09-06 14:03 UTC, crazywoola commented on api/core/model_runtime/model_providers/sagemaker/tts/tts.py
Tested with Yi

```
Node LLM run failed: [sagemaker] Error: 'NoneType' object has no attribute 'predict_stream'
```

<img width="420" alt="image" src="https://github.com/user-attachments/assets/c50d3d19-1cca-4c10-8227-a306b267cbe3">

2024-09-06 14:03 UTC, crazywoola commented on api/core/model_runtime/model_providers/sagemaker/tts/tts.py
Also can not save the configurations in Agent mode.

<img width="1652" alt="image" src="https://github.com/user-attachments/assets/29cd04c6-e2ca-4fd4-911f-479afc172dcf">

<img width="411" alt="image" src="https://github.com/user-attachments/assets/fad76226-f12c-4a5e-95a1-8edc043cf7f7">

```
Traceback (most recent call last):
  File "/Users/minibanana/Program/projects/dify/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/minibanana/Program/projects/dify/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/minibanana/Program/projects/dify/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/minibanana/Program/projects/dify/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/Users/minibanana/Program/projects/dify/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/minibanana/Program/projects/dify/api/controllers/console/setup.py", line 65, in decorated
    return view(*args, **kwargs)
  File "/Users/minibanana/Program/projects/dify/api/libs/login.py", line 93, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/minibanana/Program/projects/dify/api/controllers/console/wraps.py", line 22, in decorated
    return view(*args, **kwargs)
  File "/Users/minibanana/Program/projects/dify/api/controllers/console/app/wraps.py", line 48, in decorated_view
    return view_func(*args, **kwargs)
  File "/Users/minibanana/Program/projects/dify/api/controllers/console/app/model_config.py", line 38, in post
    new_app_model_config = new_app_model_config.from_model_config_dict(model_configuration)
  File "/Users/minibanana/Program/projects/dify/api/models/model.py", line 392, in from_model_config_dict
    self.model = json.dumps(model_config['model']) \
  File "/Users/minibanana/.pyenv/versions/3.10.14/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Users/minibanana/.pyenv/versions/3.10.14/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/minibanana/.pyenv/versions/3.10.14/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/minibanana/Program/projects/dify/api/.venv/lib/python3.10/site-packages/frozendict/__init__.py", line 31, in default
    return BaseJsonEncoder.default(self, obj)
  File "/Users/minibanana/.pyenv/versions/3.10.14/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type LLMMode is not JSON serializable
```

2024-09-09 02:10 UTC, ybalbert001 commented on api/core/model_runtime/model_providers/sagemaker/tts/tts.py
could not reproduce it

2024-09-09 02:10 UTC, ybalbert001 commented on api/core/model_runtime/model_providers/sagemaker/llm/llm.py
> +    根据给定的模型名称和端点名称，对消息进行推理。
fixed it

2024-09-09 02:10 UTC, ybalbert001 commented on api/core/model_runtime/model_providers/sagemaker/llm/llm.py
> +        # assistant_message = resp.choices[0].message
fixed it

2024-09-09 02:11 UTC, ybalbert001 commented on api/core/model_runtime/model_providers/sagemaker/tts/tts.py
fixed it

2024-09-09 02:25 UTC, crazywoola approved these changes

2024-09-09 02:34 UTC, merged