Modify model parameters
langgenius/dify pull request #8078
Opened 2024-09-07 08:59 UTC by AAEE86

# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. Close issue syntax: `Fixes #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

Fixes 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-09-07 09:12 UTC, AAEE86 commented
link #8053

2024-09-09 02:22 UTC, crazywoola requested changes
Please change the filename to lowercase as well :)

2024-09-09 02:22 UTC, crazywoola commented on api/core/model_runtime/model_providers/spark/llm/Spark-4.0Ultra.yaml
> +model: Spark-4.0Ultra
```suggestion
model: spark-4.0-ultra
```

2024-09-09 02:22 UTC, crazywoola commented on api/core/model_runtime/model_providers/spark/llm/Spark-4.0Ultra.yaml
> +  en_US: Spark 4.0Ultra
```suggestion
  en_US: Spark 4.0 Ultra
```

2024-09-09 02:22 UTC, crazywoola commented on api/core/model_runtime/model_providers/spark/llm/Spark-Lite.yaml
> +model: Spark-Lite
```suggestion
model: spark-lite
```

2024-09-09 02:22 UTC, crazywoola commented on api/core/model_runtime/model_providers/spark/llm/Spark-Max.yaml
> +model: Spark-Max
```suggestion
model: spark-max
```

2024-09-09 02:22 UTC, crazywoola commented on api/core/model_runtime/model_providers/spark/llm/Spark-Pro-128K.yaml
> +model: Spark-Pro-128K
```suggestion
model: spark-pro-128k
```

2024-09-09 02:22 UTC, crazywoola commented on api/core/model_runtime/model_providers/spark/llm/Spark-Pro-128K.yaml
> +  en_US: Spark Pro-128K
```suggestion
  en_US: Spark Pro 128K
```

2024-09-09 02:22 UTC, crazywoola commented on api/core/model_runtime/model_providers/spark/llm/Spark-Pro.yaml
> +model: Spark-Pro
```suggestion
model: spark-pro
```

2024-09-09 05:27 UTC, laipz8200 approved these changes
LGTM

2024-09-09 07:36 UTC, crazywoola approved these changes

2024-09-09 07:36 UTC, merged