Add Fireworks AI as new model provider
langgenius/dify pull request #8428
Opened 2024-09-14 07:34 UTC by yaoice

# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Fixes #8424

fireworks model references: https://fireworks.ai/models

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

<img width="1679" alt="image" src="https://github.com/user-attachments/assets/6d647293-2c78-4477-aa13-33a98421b8b5">
<img width="1688" alt="image" src="https://github.com/user-attachments/assets/293f7067-07e3-42ee-8280-d1c9682182d4">
<img width="1677" alt="image" src="https://github.com/user-attachments/assets/cbcf646d-2d3e-47e6-8438-02557bd7a327">
<img width="1671" alt="image" src="https://github.com/user-attachments/assets/804666de-7ff2-4a04-a8eb-0a26e3818c1d">
<img width="1695" alt="image" src="https://github.com/user-attachments/assets/337a73e4-2fda-44c7-a044-a1999f0fb02c">
<img width="1683" alt="image" src="https://github.com/user-attachments/assets/9c73901d-0bc2-45e6-9c2a-7e381903aad1">

2024-09-15 09:15 UTC, crazywoola commented on api/core/model_runtime/model_providers/fireworks/_assets/icon_l_en.svg
It seems that the logo is breaking the UI

2024-09-15 09:15 UTC, crazywoola requested changes
See comments

2024-09-15 15:00 UTC, yaoice commented on api/core/model_runtime/model_providers/fireworks/_assets/icon_l_en.svg
I hava update the icon_l_en.svg to fit the UI as following：
![image](https://github.com/user-attachments/assets/78668173-3603-43bf-ab0a-7d8bfc69fba8)

2024-09-15 15:03 UTC, yaoice commented
> See comments

@crazywoola I have done, pls review it again.

2024-09-22 02:12 UTC, crazywoola approved these changes

2024-09-22 02:13 UTC, merged