feat: support workflow multi version recovery
langgenius/dify pull request #8484
Opened 2024-09-16 10:11 UTC by luckylhb90

# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Feat: 
support workflow multi version recovery

<img width="473" alt="image" src="https://github.com/user-attachments/assets/d844157b-bd3c-4621-a8ee-ce34c3c9af5a">

<img width="418" alt="image" src="https://github.com/user-attachments/assets/88fb6d9d-d78c-4347-bbf2-7589cd47cd59">

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-09-16 15:14 UTC, RahulVadisetty91 reviewed
![w5678u](https://github.com/user-attachments/assets/9c3afb47-8611-46d2-8c88-2e882b4911f6)

Refactor to catch more specific exceptions that are likely to occur in your service.

2024-12-20 02:44 UTC, warren830 commented
@luckylhb90 @RahulVadisetty91 @rainchen @hobo-l-20230331 Hi guys, any update for this pr? We really really need this!

2024-12-20 07:13 UTC, laipz8200 commented
Hi @luckylhb90, sorry for the late reply, would you like to resolve those conflicts?

2024-12-20 08:35 UTC, warren830 commented
@crazywoola hello, need to fix python style check

2024-12-20 08:57 UTC, crazywoola approved these changes
LGTM @laipz8200

2024-12-26 15:56 UTC, laipz8200 commented
Hi @luckylhb90, could you sync the code with the main branch? We've added a new Mypy checker and it needs to be passed.

2024-12-26 16:06 UTC, laipz8200 requested changes

2024-12-26 16:06 UTC, laipz8200 commented on api/services/workflow_service.py
> +                workflow.version = version_datetime.strftime("%Y-%m-%d %H:%M:%S")
update a db model for API response it's not a good way, please consider doing this convert in the front end.

The same issue is on L99.

2024-12-26 16:06 UTC, laipz8200 commented on api/controllers/console/app/workflow.py
> +api.add_resource(PublishedAllWorkflowApi, "/apps/<uuid:app_id>/workflows/publish/all")
IMO, this route name should be `/apps/<uuid:app_id>/workflows`

2024-12-27 10:20 UTC, laipz8200 commented
Since the author hasn’t responded for a long time, I think we can close this PR and complete it in #11990.

2024-12-27 13:05 UTC, closed without merging