add Qwen custom add model interface
langgenius/dify pull request #8565
Opened 2024-09-19 14:27 UTC by AAEE86

# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. Close issue syntax: `Fixes #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

Fixes #8438

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-09-19 15:05 UTC, AAEE86 commented
@Laipz8200 Is it correct to make modifications according to the md document and other LLM files?

2024-09-20 02:52 UTC, AAEE86 commented
![Quicker_20240920_104851](https://github.com/user-attachments/assets/99b3b5ab-d075-4e00-b6b4-4628f7f99fbf)

2024-09-20 03:38 UTC, laipz8200 requested changes

2024-09-20 03:38 UTC, laipz8200 commented on api/core/model_runtime/model_providers/tongyi/llm/llm.py
> +        用于定义自定义模型的 schema
Please comment on your code in English.

2024-09-20 03:40 UTC, laipz8200 commented
Hi @AAEE86, Please take a look at my comments above. You should run the `/dev/reformat` script before your commit.

2024-09-21 09:40 UTC, AAEE86 commented
> Hi @AAEE86, Please take a look at my comments above. You should run the `/dev/reformat` script before your commit.

pls merge.

2024-09-21 14:51 UTC, crazywoola approved these changes

2024-09-21 14:52 UTC, merged