Feat:Add Pinecone as a new vector database
langgenius/dify pull request #8926
Opened 2024-09-30 09:49 UTC by Howe829

# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. Close issue syntax: `Fixes #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

Fixes #8892 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-09-30 14:58 UTC, yaoice requested changes
See comments

2024-09-30 14:58 UTC, yaoice commented on api/tests/integration_tests/vdb/pinecone/test_pinecone.py
please add ut in `dev/pytest/pytest_vdb.sh` to execute.

2024-10-08 02:49 UTC, Howe829 commented
> See comments

Hi! I'm glad to see your comment, I've resolved it.PTAL.

2024-10-09 06:16 UTC, crazywoola commented
@Howe829 Hello, please resolve deps issue here.

2024-10-09 10:16 UTC, Howe829 commented
> @Howe829 Hello, please resolve deps issue here.

Hi there! I've resolved the deps issues.The Pytest failed the due to the api key  provided in test_pinecone.py is not real.

2024-10-10 02:06 UTC, yaoice commented
> > @Howe829 Hello, please resolve deps issue here.
> 
> Hi there! I've resolved the deps issues.The Pytest failed due to the api key provided in test_pinecone.py is not real.

I think you need to mock api with calling pinecone to run pytest successfully.

2024-10-10 03:54 UTC, Howe829 commented
> > > @Howe829 Hello, please resolve deps issue here.
> > 
> > 
> > Hi there! I've resolved the deps issues.The Pytest failed due to the api key provided in test_pinecone.py is not real.
> 
> I think you need to mock api with calling pinecone to run pytest successfully.

Thanks for your advice, all checks have passed.

2024-10-14 13:41 UTC, crazywoola commented
Seems there more conflicts here.

2024-10-15 01:49 UTC, Howe829 commented
> Seems there more conflicts here.

Resolved.PTAL @crazywoola

2024-10-21 01:34 UTC, crazywoola commented
@Howe829 Hello there are some errors in the tests.

2024-10-21 10:04 UTC, yaoice commented on api/tests/integration_tests/vdb/pinecone/test_pinecone.py
> +    mock.Index.return_value.query.return_value = {
I think it is more reasonable to mock the methods of pindex.delete, query, and upsert.

2024-10-29 06:49 UTC, closed without merging