feat: add models for gitee.ai
langgenius/dify pull request #9490
Opened 2024-10-18 08:41 UTC by fchange

# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [X] Please open an issue before creating a PR or link to an existing issue
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

This pull request introduces support for Gitee AI as a new model provider.  `Fixes #<9243>`, [link](https://github.com/langgenius/dify/issues/9243)

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions
The changes were tested using manually filled credentials.
![img_v3_02f3_41d4fba0-ccad-4750-80ee-9f55ddec38bg](https://github.com/user-attachments/assets/31723e9c-f71c-4f46-b6ff-527a7dcfb068)

2024-10-18 09:27 UTC, crazywoola requested changes
Tests are required for new providers.

2024-10-18 09:32 UTC, bluishoul commented on api/core/model_runtime/model_providers/gitee_ai/gitee_ai.py
> +        pass
Validate credential with API： https://ai.gitee.com/docs/openapi/v1#tag/account/GET/{namespace}/profile

2024-10-21 03:25 UTC, fchange commented
Tests have been completed and verified.

2024-10-22 14:04 UTC, crazywoola commented
> validate_credentials has been implemented and self-tested.

I mean you need to add tests here like this one 
https://github.com/langgenius/dify/blob/7c0b159a81f099c5089c96ba77b32d592e5787b8/api/tests/integration_tests/model_runtime/openai/test_llm.py

2024-10-24 02:43 UTC, fchange commented
Added tests，because they use the real Gitee AI service, which requires a correctly filled access_token to run successfully. Therefore, the test command was not added to pytest_model_runtime.sh
@crazywoola

2024-10-24 02:59 UTC, bluishoul commented
@crazywoola you can sign up Gitee AI, and use the free token(100 requests limit per day) to run the tests: https://ai.gitee.com/dashboard/settings/tokens

<img width="914" alt="image" src="https://github.com/user-attachments/assets/58a1d319-7ac2-44ac-9257-a74647c2857d">

2024-10-28 08:52 UTC, crazywoola approved these changes

2024-10-28 08:52 UTC, merged