feat: Iteration node support parallel mode
langgenius/dify pull request #9493
Opened 2024-10-18 09:12 UTC by Nov1c444

# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Iteration Node supports parallel mode. And add three error handle mode. 

Fixes 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-10-29 05:58 UTC, iamjoel approved these changes, later dismissed

2024-10-30 04:49 UTC, laipz8200 requested changes

2024-10-30 04:49 UTC, laipz8200 commented on api/core/workflow/nodes/iteration/iteration_node.py
> +        graph_engine,
please add type hints here.

2024-10-30 04:49 UTC, laipz8200 commented on api/core/workflow/nodes/iteration/iteration_node.py
> +        iteration_graph,
please add type hints here.

2024-10-30 04:49 UTC, laipz8200 commented on api/core/workflow/nodes/iteration/iteration_node.py
> +        graph_engine,
please add type hints here.

2024-10-30 04:49 UTC, laipz8200 commented on api/core/workflow/nodes/iteration/iteration_node.py
> +        iteration_graph,
please add type hints here.

2024-10-30 04:49 UTC, laipz8200 commented on api/core/workflow/nodes/iteration/iteration_node.py
> +        index,
please add type hints here.

2024-10-30 04:49 UTC, laipz8200 commented on api/core/workflow/nodes/iteration/iteration_node.py
> +        item,
please add type hints here.

2024-10-30 04:49 UTC, laipz8200 commented on api/core/workflow/nodes/iteration/entities.py
> +class ErrorHandleMode(Enum):
I think this enum should inherit from `str`.
```suggestion
class ErrorHandleMode(str, Enum):
```

2024-10-30 04:49 UTC, laipz8200 commented on api/core/workflow/nodes/iteration/entities.py
> +    def to_json(self):
What is this method used for?

2024-10-30 04:49 UTC, laipz8200 commented on api/core/workflow/nodes/iteration/entities.py
> +    def from_json(cls, value):
What is this method used for?

2024-11-04 05:30 UTC, laipz8200 approved these changes, later dismissed

2024-11-04 05:30 UTC, laipz8200 commented on api/core/workflow/nodes/iteration/entities.py
> +    REMOVE_ABNORMAL_OUTPUT = "Remove abnormal output"
The enumeration here can use lowercase letters + hyphen (-), just like in other places.

2024-11-05 02:32 UTC, laipz8200 approved these changes

2024-11-05 02:32 UTC, merged

2024-12-12 00:17 UTC, detongz commented
Iteration node parallel mode is great, but I find that it wont work when i have parallel llm nodes running within it:
![image](https://github.com/user-attachments/assets/e7a7d1b0-c541-420d-a1fd-956f63599c53)
![image](https://github.com/user-attachments/assets/0e79c0e3-da5e-4a00-8d00-67662646142e)

After iteration node parallel mode the entire loop blocks at its first node and stucked.
![image](https://github.com/user-attachments/assets/d42a3643-9088-4031-b95e-c4015a18c754)

2024-12-12 03:26 UTC, Nov1c444 commented
> Iteration node parallel mode is great, but I find that it wont work when i have parallel llm nodes running within it: ![image](https://private-user-images.githubusercontent.com/9070847/394960792-e7a7d1b0-c541-420d-a1fd-956f63599c53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NzQxMTEsIm5iZiI6MTczMzk3MzgxMSwicGF0aCI6Ii85MDcwODQ3LzM5NDk2MDc5Mi1lN2E3ZDFiMC1jNTQxLTQyMGQtYTFmZC05NTZmNjM1OTljNTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTJUMDMyMzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzQzZjkyMzY5MGI2NGViOTJhMmQ1OTIxYTIyMGM5NjhiODNiM2YwMmJhMzEyNDM5NTZlYzkzZTJlOGQ2ZDA5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lKlfkI1E_ZN1_Sghb31sGvz21U7sCCsENYf2_19d7Ng) ![image](https://private-user-images.githubusercontent.com/9070847/394960831-0e79c0e3-da5e-4a00-8d00-67662646142e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NzQxMTEsIm5iZiI6MTczMzk3MzgxMSwicGF0aCI6Ii85MDcwODQ3LzM5NDk2MDgzMS0wZTc5YzBlMy1kYTVlLTRhMDAtOGQwMC02NzY2MjY0NjE0MmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTJUMDMyMzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWM3MjU4MTUyZDkyNzA0NDk3OWFmNWZlMzU4NjQ3NDkxMTgwMzlmOTUzY2ZhMTgzY2Y4ZThkNmU2ZTAxYjliYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.cVNVj7Kvkof7dDVNmoVK50q3MalcKOlJnkyaiuxjSG4)
> 
> After iteration node parallel mode the entire loop blocks at its first node and stucked. ![image](https://private-user-images.githubusercontent.com/9070847/394960861-d42a3643-9088-4031-b95e-c4015a18c754.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NzQxMTEsIm5iZiI6MTczMzk3MzgxMSwicGF0aCI6Ii85MDcwODQ3LzM5NDk2MDg2MS1kNDJhMzY0My05MDg4LTQwMzEtYjk1ZS1jNDAxNWExOGM3NTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTJUMDMyMzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTQzZTY1M2UyZmI4OWQ0NmYzYTc5NDU5NjQ1YTU1NTQ2NjA1YmY2YjkzNDAwNGRmYzA0N2RiZmRmODBiODFmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.8JkNpJUdnxqmZF5A1ldHt79LkVDMiqnkOTowSALx6zc)
Sorry, I tried to build a similar workflow, but couldn't reproduce your issue. Could you please create an issue and provide us with more information?